// Copyright 2021 The ciscobcs AUTHORS. All rights reserved.
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package ciscosmartbonding

// GetDataBase64 returns the DataBase64 field if it's non-nil, zero value otherwise.
func (a *AttachmentsHolder) GetDataBase64() string {
	if a == nil || a.DataBase64 == nil {
		return ""
	}
	return *a.DataBase64
}

// GetFileName returns the FileName field if it's non-nil, zero value otherwise.
func (a *AttachmentsHolder) GetFileName() string {
	if a == nil || a.FileName == nil {
		return ""
	}
	return *a.FileName
}

// GetNR returns the NR field.
func (a *AttachmentsHolder) GetNR() *float32 {
	if a == nil {
		return nil
	}
	return a.NR
}

// GetActivityType returns the ActivityType field.
func (c *CallActivitiesHolder) GetActivityType() *EntityTypesHolder {
	if c == nil {
		return nil
	}
	return c.ActivityType
}

// GetBackTime returns the BackTime field.
func (c *CallActivitiesHolder) GetBackTime() *CiscoDateTime {
	if c == nil {
		return nil
	}
	return c.BackTime
}

// GetBPPShortName returns the BPPShortName field if it's non-nil, zero value otherwise.
func (c *CallActivitiesHolder) GetBPPShortName() string {
	if c == nil || c.BPPShortName == nil {
		return ""
	}
	return *c.BPPShortName
}

// GetBusyTime returns the BusyTime field.
func (c *CallActivitiesHolder) GetBusyTime() *CiscoDateTime {
	if c == nil {
		return nil
	}
	return c.BusyTime
}

// GetDistance returns the Distance field.
func (c *CallActivitiesHolder) GetDistance() *int32 {
	if c == nil {
		return nil
	}
	return c.Distance
}

// GetTravelBackMinutes returns the TravelBackMinutes field.
func (c *CallActivitiesHolder) GetTravelBackMinutes() *int32 {
	if c == nil {
		return nil
	}
	return c.TravelBackMinutes
}

// GetTravelBackRemarks returns the TravelBackRemarks field if it's non-nil, zero value otherwise.
func (c *CallActivitiesHolder) GetTravelBackRemarks() string {
	if c == nil || c.TravelBackRemarks == nil {
		return ""
	}
	return *c.TravelBackRemarks
}

// GetTravelMinutes returns the TravelMinutes field.
func (c *CallActivitiesHolder) GetTravelMinutes() *int32 {
	if c == nil {
		return nil
	}
	return c.TravelMinutes
}

// GetTravelRemarks returns the TravelRemarks field if it's non-nil, zero value otherwise.
func (c *CallActivitiesHolder) GetTravelRemarks() string {
	if c == nil || c.TravelRemarks == nil {
		return ""
	}
	return *c.TravelRemarks
}

// GetWorkEndTime returns the WorkEndTime field.
func (c *CallActivitiesHolder) GetWorkEndTime() *CiscoDateTime {
	if c == nil {
		return nil
	}
	return c.WorkEndTime
}

// GetWorkMinutes returns the WorkMinutes field.
func (c *CallActivitiesHolder) GetWorkMinutes() *int32 {
	if c == nil {
		return nil
	}
	return c.WorkMinutes
}

// GetWorkRemarks returns the WorkRemarks field if it's non-nil, zero value otherwise.
func (c *CallActivitiesHolder) GetWorkRemarks() string {
	if c == nil || c.WorkRemarks == nil {
		return ""
	}
	return *c.WorkRemarks
}

// GetWorkStartTime returns the WorkStartTime field.
func (c *CallActivitiesHolder) GetWorkStartTime() *CiscoDateTime {
	if c == nil {
		return nil
	}
	return c.WorkStartTime
}

// GetField1 returns the Field1 field.
func (c *CallAdditionalsHolder) GetField1() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field1
}

// GetField10 returns the Field10 field.
func (c *CallAdditionalsHolder) GetField10() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field10
}

// GetField11 returns the Field11 field.
func (c *CallAdditionalsHolder) GetField11() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field11
}

// GetField12 returns the Field12 field.
func (c *CallAdditionalsHolder) GetField12() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field12
}

// GetField13 returns the Field13 field.
func (c *CallAdditionalsHolder) GetField13() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field13
}

// GetField14 returns the Field14 field.
func (c *CallAdditionalsHolder) GetField14() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field14
}

// GetField15 returns the Field15 field.
func (c *CallAdditionalsHolder) GetField15() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field15
}

// GetField16 returns the Field16 field.
func (c *CallAdditionalsHolder) GetField16() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field16
}

// GetField17 returns the Field17 field.
func (c *CallAdditionalsHolder) GetField17() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field17
}

// GetField18 returns the Field18 field.
func (c *CallAdditionalsHolder) GetField18() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field18
}

// GetField19 returns the Field19 field.
func (c *CallAdditionalsHolder) GetField19() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field19
}

// GetField2 returns the Field2 field.
func (c *CallAdditionalsHolder) GetField2() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field2
}

// GetField20 returns the Field20 field.
func (c *CallAdditionalsHolder) GetField20() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field20
}

// GetField21 returns the Field21 field.
func (c *CallAdditionalsHolder) GetField21() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field21
}

// GetField22 returns the Field22 field.
func (c *CallAdditionalsHolder) GetField22() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field22
}

// GetField23 returns the Field23 field.
func (c *CallAdditionalsHolder) GetField23() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field23
}

// GetField24 returns the Field24 field.
func (c *CallAdditionalsHolder) GetField24() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field24
}

// GetField25 returns the Field25 field.
func (c *CallAdditionalsHolder) GetField25() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field25
}

// GetField26 returns the Field26 field.
func (c *CallAdditionalsHolder) GetField26() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field26
}

// GetField27 returns the Field27 field.
func (c *CallAdditionalsHolder) GetField27() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field27
}

// GetField28 returns the Field28 field.
func (c *CallAdditionalsHolder) GetField28() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field28
}

// GetField29 returns the Field29 field.
func (c *CallAdditionalsHolder) GetField29() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field29
}

// GetField3 returns the Field3 field.
func (c *CallAdditionalsHolder) GetField3() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field3
}

// GetField30 returns the Field30 field.
func (c *CallAdditionalsHolder) GetField30() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field30
}

// GetField31 returns the Field31 field.
func (c *CallAdditionalsHolder) GetField31() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field31
}

// GetField32 returns the Field32 field.
func (c *CallAdditionalsHolder) GetField32() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field32
}

// GetField33 returns the Field33 field.
func (c *CallAdditionalsHolder) GetField33() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field33
}

// GetField34 returns the Field34 field.
func (c *CallAdditionalsHolder) GetField34() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field34
}

// GetField35 returns the Field35 field.
func (c *CallAdditionalsHolder) GetField35() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field35
}

// GetField36 returns the Field36 field.
func (c *CallAdditionalsHolder) GetField36() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field36
}

// GetField37 returns the Field37 field.
func (c *CallAdditionalsHolder) GetField37() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field37
}

// GetField38 returns the Field38 field.
func (c *CallAdditionalsHolder) GetField38() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field38
}

// GetField39 returns the Field39 field.
func (c *CallAdditionalsHolder) GetField39() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field39
}

// GetField4 returns the Field4 field.
func (c *CallAdditionalsHolder) GetField4() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field4
}

// GetField40 returns the Field40 field.
func (c *CallAdditionalsHolder) GetField40() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field40
}

// GetField41 returns the Field41 field.
func (c *CallAdditionalsHolder) GetField41() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field41
}

// GetField42 returns the Field42 field.
func (c *CallAdditionalsHolder) GetField42() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field42
}

// GetField43 returns the Field43 field.
func (c *CallAdditionalsHolder) GetField43() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field43
}

// GetField44 returns the Field44 field.
func (c *CallAdditionalsHolder) GetField44() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field44
}

// GetField45 returns the Field45 field.
func (c *CallAdditionalsHolder) GetField45() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field45
}

// GetField46 returns the Field46 field.
func (c *CallAdditionalsHolder) GetField46() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field46
}

// GetField47 returns the Field47 field.
func (c *CallAdditionalsHolder) GetField47() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field47
}

// GetField48 returns the Field48 field.
func (c *CallAdditionalsHolder) GetField48() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field48
}

// GetField49 returns the Field49 field.
func (c *CallAdditionalsHolder) GetField49() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field49
}

// GetField5 returns the Field5 field.
func (c *CallAdditionalsHolder) GetField5() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field5
}

// GetField50 returns the Field50 field.
func (c *CallAdditionalsHolder) GetField50() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field50
}

// GetField51 returns the Field51 field.
func (c *CallAdditionalsHolder) GetField51() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field51
}

// GetField52 returns the Field52 field.
func (c *CallAdditionalsHolder) GetField52() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field52
}

// GetField53 returns the Field53 field.
func (c *CallAdditionalsHolder) GetField53() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field53
}

// GetField54 returns the Field54 field.
func (c *CallAdditionalsHolder) GetField54() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field54
}

// GetField55 returns the Field55 field.
func (c *CallAdditionalsHolder) GetField55() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field55
}

// GetField56 returns the Field56 field.
func (c *CallAdditionalsHolder) GetField56() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field56
}

// GetField57 returns the Field57 field.
func (c *CallAdditionalsHolder) GetField57() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field57
}

// GetField58 returns the Field58 field.
func (c *CallAdditionalsHolder) GetField58() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field58
}

// GetField59 returns the Field59 field.
func (c *CallAdditionalsHolder) GetField59() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field59
}

// GetField6 returns the Field6 field.
func (c *CallAdditionalsHolder) GetField6() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field6
}

// GetField60 returns the Field60 field.
func (c *CallAdditionalsHolder) GetField60() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field60
}

// GetField61 returns the Field61 field.
func (c *CallAdditionalsHolder) GetField61() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field61
}

// GetField62 returns the Field62 field.
func (c *CallAdditionalsHolder) GetField62() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field62
}

// GetField63 returns the Field63 field.
func (c *CallAdditionalsHolder) GetField63() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field63
}

// GetField64 returns the Field64 field.
func (c *CallAdditionalsHolder) GetField64() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field64
}

// GetField7 returns the Field7 field.
func (c *CallAdditionalsHolder) GetField7() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field7
}

// GetField8 returns the Field8 field.
func (c *CallAdditionalsHolder) GetField8() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field8
}

// GetField9 returns the Field9 field.
func (c *CallAdditionalsHolder) GetField9() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.Field9
}

// GetFunctionPort returns the FunctionPort field.
func (c *CallAdditionalsHolder) GetFunctionPort() *StringKeyField {
	if c == nil {
		return nil
	}
	return c.FunctionPort
}

// GetPosNr returns the PosNr field.
func (c *CallAdditionalsHolder) GetPosNr() *IntegerKeyField {
	if c == nil {
		return nil
	}
	return c.PosNr
}

// GetUrl1 returns the Url1 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrl1() string {
	if c == nil || c.Url1 == nil {
		return ""
	}
	return *c.Url1
}

// GetUrl2 returns the Url2 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrl2() string {
	if c == nil || c.Url2 == nil {
		return ""
	}
	return *c.Url2
}

// GetUrl3 returns the Url3 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrl3() string {
	if c == nil || c.Url3 == nil {
		return ""
	}
	return *c.Url3
}

// GetUrl4 returns the Url4 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrl4() string {
	if c == nil || c.Url4 == nil {
		return ""
	}
	return *c.Url4
}

// GetUrl5 returns the Url5 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrl5() string {
	if c == nil || c.Url5 == nil {
		return ""
	}
	return *c.Url5
}

// GetUrl6 returns the Url6 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrl6() string {
	if c == nil || c.Url6 == nil {
		return ""
	}
	return *c.Url6
}

// GetUrl7 returns the Url7 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrl7() string {
	if c == nil || c.Url7 == nil {
		return ""
	}
	return *c.Url7
}

// GetUrl8 returns the Url8 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrl8() string {
	if c == nil || c.Url8 == nil {
		return ""
	}
	return *c.Url8
}

// GetUrlName1 returns the UrlName1 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrlName1() string {
	if c == nil || c.UrlName1 == nil {
		return ""
	}
	return *c.UrlName1
}

// GetUrlName2 returns the UrlName2 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrlName2() string {
	if c == nil || c.UrlName2 == nil {
		return ""
	}
	return *c.UrlName2
}

// GetUrlName3 returns the UrlName3 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrlName3() string {
	if c == nil || c.UrlName3 == nil {
		return ""
	}
	return *c.UrlName3
}

// GetUrlName4 returns the UrlName4 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrlName4() string {
	if c == nil || c.UrlName4 == nil {
		return ""
	}
	return *c.UrlName4
}

// GetUrlName5 returns the UrlName5 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrlName5() string {
	if c == nil || c.UrlName5 == nil {
		return ""
	}
	return *c.UrlName5
}

// GetUrlName6 returns the UrlName6 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrlName6() string {
	if c == nil || c.UrlName6 == nil {
		return ""
	}
	return *c.UrlName6
}

// GetUrlName7 returns the UrlName7 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrlName7() string {
	if c == nil || c.UrlName7 == nil {
		return ""
	}
	return *c.UrlName7
}

// GetUrlName8 returns the UrlName8 field if it's non-nil, zero value otherwise.
func (c *CallAdditionalsHolder) GetUrlName8() string {
	if c == nil || c.UrlName8 == nil {
		return ""
	}
	return *c.UrlName8
}

// GetChargingTypes returns the ChargingTypes field.
func (c *CallCalculationsHolder) GetChargingTypes() *ChargingTypesHolder {
	if c == nil {
		return nil
	}
	return c.ChargingTypes
}

// GetContractShortName returns the ContractShortName field if it's non-nil, zero value otherwise.
func (c *CallCalculationsHolder) GetContractShortName() string {
	if c == nil || c.ContractShortName == nil {
		return ""
	}
	return *c.ContractShortName
}

// GetRequestedWorkEndTime returns the RequestedWorkEndTime field.
func (c *CallCalculationsHolder) GetRequestedWorkEndTime() *CiscoDateTime {
	if c == nil {
		return nil
	}
	return c.RequestedWorkEndTime
}

// GetRevenue returns the Revenue field.
func (c *CallCalculationsHolder) GetRevenue() *float32 {
	if c == nil {
		return nil
	}
	return c.Revenue
}

// GetServiceType returns the ServiceType field if it's non-nil, zero value otherwise.
func (c *CallCalculationsHolder) GetServiceType() string {
	if c == nil || c.ServiceType == nil {
		return ""
	}
	return *c.ServiceType
}

// GetAttachments returns the Attachments field if it's non-nil, zero value otherwise.
func (c *CallData) GetAttachments() []AttachmentsHolder {
	if c == nil || c.Attachments == nil {
		return nil
	}
	return *c.Attachments
}

// GetCallActivities returns the CallActivities field if it's non-nil, zero value otherwise.
func (c *CallData) GetCallActivities() []CallActivitiesHolder {
	if c == nil || c.CallActivities == nil {
		return nil
	}
	return *c.CallActivities
}

// GetCallAdditionals returns the CallAdditionals field if it's non-nil, zero value otherwise.
func (c *CallData) GetCallAdditionals() []CallAdditionalsHolder {
	if c == nil || c.CallAdditionals == nil {
		return nil
	}
	return *c.CallAdditionals
}

// GetCallCalculations returns the CallCalculations field.
func (c *CallData) GetCallCalculations() *CallCalculationsHolder {
	if c == nil {
		return nil
	}
	return c.CallCalculations
}

// GetCallStates returns the CallStates field.
func (c *CallData) GetCallStates() *CallSystemCodesHolder {
	if c == nil {
		return nil
	}
	return c.CallStates
}

// GetContractElements returns the ContractElements field.
func (c *CallData) GetContractElements() *InboundContractElementsHolder {
	if c == nil {
		return nil
	}
	return c.ContractElements
}

// GetContracts returns the Contracts field.
func (c *CallData) GetContracts() *InboundContractsHolder {
	if c == nil {
		return nil
	}
	return c.Contracts
}

// GetControl returns the Control field.
func (c *CallData) GetControl() *ControlFlagsHolder {
	if c == nil {
		return nil
	}
	return c.Control
}

// GetDeviceMovements returns the DeviceMovements field if it's non-nil, zero value otherwise.
func (c *CallData) GetDeviceMovements() []DeviceMovementsHolder {
	if c == nil || c.DeviceMovements == nil {
		return nil
	}
	return *c.DeviceMovements
}

// GetDevices returns the Devices field.
func (c *CallData) GetDevices() *DevicesHolder {
	if c == nil {
		return nil
	}
	return c.Devices
}

// GetExtTableValues returns the ExtTableValues field.
func (c *CallData) GetExtTableValues() *CallExtensionsHolder {
	if c == nil {
		return nil
	}
	return c.ExtTableValues
}

// GetFailureTypes returns the FailureTypes field.
func (c *CallData) GetFailureTypes() *CallSystemCodesHolder {
	if c == nil {
		return nil
	}
	return c.FailureTypes
}

// GetImpacts returns the Impacts field.
func (c *CallData) GetImpacts() *CallSystemCodesHolder {
	if c == nil {
		return nil
	}
	return c.Impacts
}

// GetLocations returns the Locations field.
func (c *CallData) GetLocations() *LocationsHolder {
	if c == nil {
		return nil
	}
	return c.Locations
}

// GetParentCall returns the ParentCall field.
func (c *CallData) GetParentCall() *ParentCallsHolder {
	if c == nil {
		return nil
	}
	return c.ParentCall
}

// GetPriorities returns the Priorities field.
func (c *CallData) GetPriorities() *CallSystemCodesHolder {
	if c == nil {
		return nil
	}
	return c.Priorities
}

// GetProblemTypes returns the ProblemTypes field.
func (c *CallData) GetProblemTypes() *CallSystemCodesHolder {
	if c == nil {
		return nil
	}
	return c.ProblemTypes
}

// GetQueues1 returns the Queues1 field.
func (c *CallData) GetQueues1() *QueuesHolder {
	if c == nil {
		return nil
	}
	return c.Queues1
}

// GetQueues2 returns the Queues2 field.
func (c *CallData) GetQueues2() *QueuesHolder {
	if c == nil {
		return nil
	}
	return c.Queues2
}

// GetQueues3 returns the Queues3 field.
func (c *CallData) GetQueues3() *QueuesHolder {
	if c == nil {
		return nil
	}
	return c.Queues3
}

// GetRequestTypes returns the RequestTypes field.
func (c *CallData) GetRequestTypes() *CallSystemCodesHolder {
	if c == nil {
		return nil
	}
	return c.RequestTypes
}

// GetSeverities returns the Severities field.
func (c *CallData) GetSeverities() *CallSystemCodesHolder {
	if c == nil {
		return nil
	}
	return c.Severities
}

// GetUrgency returns the Urgency field.
func (c *CallData) GetUrgency() *CallSystemCodesHolder {
	if c == nil {
		return nil
	}
	return c.Urgency
}

// GetField1 returns the Field1 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField1() string {
	if c == nil || c.Field1 == nil {
		return ""
	}
	return *c.Field1
}

// GetField10 returns the Field10 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField10() string {
	if c == nil || c.Field10 == nil {
		return ""
	}
	return *c.Field10
}

// GetField100 returns the Field100 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField100() string {
	if c == nil || c.Field100 == nil {
		return ""
	}
	return *c.Field100
}

// GetField101 returns the Field101 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField101() string {
	if c == nil || c.Field101 == nil {
		return ""
	}
	return *c.Field101
}

// GetField102 returns the Field102 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField102() string {
	if c == nil || c.Field102 == nil {
		return ""
	}
	return *c.Field102
}

// GetField103 returns the Field103 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField103() string {
	if c == nil || c.Field103 == nil {
		return ""
	}
	return *c.Field103
}

// GetField104 returns the Field104 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField104() string {
	if c == nil || c.Field104 == nil {
		return ""
	}
	return *c.Field104
}

// GetField105 returns the Field105 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField105() string {
	if c == nil || c.Field105 == nil {
		return ""
	}
	return *c.Field105
}

// GetField106 returns the Field106 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField106() string {
	if c == nil || c.Field106 == nil {
		return ""
	}
	return *c.Field106
}

// GetField107 returns the Field107 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField107() string {
	if c == nil || c.Field107 == nil {
		return ""
	}
	return *c.Field107
}

// GetField108 returns the Field108 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField108() string {
	if c == nil || c.Field108 == nil {
		return ""
	}
	return *c.Field108
}

// GetField109 returns the Field109 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField109() string {
	if c == nil || c.Field109 == nil {
		return ""
	}
	return *c.Field109
}

// GetField11 returns the Field11 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField11() string {
	if c == nil || c.Field11 == nil {
		return ""
	}
	return *c.Field11
}

// GetField110 returns the Field110 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField110() string {
	if c == nil || c.Field110 == nil {
		return ""
	}
	return *c.Field110
}

// GetField111 returns the Field111 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField111() string {
	if c == nil || c.Field111 == nil {
		return ""
	}
	return *c.Field111
}

// GetField112 returns the Field112 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField112() string {
	if c == nil || c.Field112 == nil {
		return ""
	}
	return *c.Field112
}

// GetField113 returns the Field113 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField113() string {
	if c == nil || c.Field113 == nil {
		return ""
	}
	return *c.Field113
}

// GetField114 returns the Field114 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField114() string {
	if c == nil || c.Field114 == nil {
		return ""
	}
	return *c.Field114
}

// GetField115 returns the Field115 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField115() string {
	if c == nil || c.Field115 == nil {
		return ""
	}
	return *c.Field115
}

// GetField116 returns the Field116 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField116() string {
	if c == nil || c.Field116 == nil {
		return ""
	}
	return *c.Field116
}

// GetField117 returns the Field117 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField117() string {
	if c == nil || c.Field117 == nil {
		return ""
	}
	return *c.Field117
}

// GetField118 returns the Field118 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField118() string {
	if c == nil || c.Field118 == nil {
		return ""
	}
	return *c.Field118
}

// GetField119 returns the Field119 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField119() string {
	if c == nil || c.Field119 == nil {
		return ""
	}
	return *c.Field119
}

// GetField12 returns the Field12 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField12() string {
	if c == nil || c.Field12 == nil {
		return ""
	}
	return *c.Field12
}

// GetField120 returns the Field120 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField120() string {
	if c == nil || c.Field120 == nil {
		return ""
	}
	return *c.Field120
}

// GetField121 returns the Field121 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField121() string {
	if c == nil || c.Field121 == nil {
		return ""
	}
	return *c.Field121
}

// GetField122 returns the Field122 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField122() string {
	if c == nil || c.Field122 == nil {
		return ""
	}
	return *c.Field122
}

// GetField123 returns the Field123 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField123() string {
	if c == nil || c.Field123 == nil {
		return ""
	}
	return *c.Field123
}

// GetField124 returns the Field124 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField124() string {
	if c == nil || c.Field124 == nil {
		return ""
	}
	return *c.Field124
}

// GetField125 returns the Field125 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField125() string {
	if c == nil || c.Field125 == nil {
		return ""
	}
	return *c.Field125
}

// GetField126 returns the Field126 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField126() string {
	if c == nil || c.Field126 == nil {
		return ""
	}
	return *c.Field126
}

// GetField127 returns the Field127 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField127() string {
	if c == nil || c.Field127 == nil {
		return ""
	}
	return *c.Field127
}

// GetField128 returns the Field128 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField128() string {
	if c == nil || c.Field128 == nil {
		return ""
	}
	return *c.Field128
}

// GetField13 returns the Field13 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField13() string {
	if c == nil || c.Field13 == nil {
		return ""
	}
	return *c.Field13
}

// GetField14 returns the Field14 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField14() string {
	if c == nil || c.Field14 == nil {
		return ""
	}
	return *c.Field14
}

// GetField15 returns the Field15 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField15() string {
	if c == nil || c.Field15 == nil {
		return ""
	}
	return *c.Field15
}

// GetField16 returns the Field16 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField16() string {
	if c == nil || c.Field16 == nil {
		return ""
	}
	return *c.Field16
}

// GetField17 returns the Field17 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField17() string {
	if c == nil || c.Field17 == nil {
		return ""
	}
	return *c.Field17
}

// GetField18 returns the Field18 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField18() string {
	if c == nil || c.Field18 == nil {
		return ""
	}
	return *c.Field18
}

// GetField19 returns the Field19 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField19() string {
	if c == nil || c.Field19 == nil {
		return ""
	}
	return *c.Field19
}

// GetField2 returns the Field2 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField2() string {
	if c == nil || c.Field2 == nil {
		return ""
	}
	return *c.Field2
}

// GetField20 returns the Field20 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField20() string {
	if c == nil || c.Field20 == nil {
		return ""
	}
	return *c.Field20
}

// GetField21 returns the Field21 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField21() string {
	if c == nil || c.Field21 == nil {
		return ""
	}
	return *c.Field21
}

// GetField22 returns the Field22 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField22() string {
	if c == nil || c.Field22 == nil {
		return ""
	}
	return *c.Field22
}

// GetField23 returns the Field23 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField23() string {
	if c == nil || c.Field23 == nil {
		return ""
	}
	return *c.Field23
}

// GetField24 returns the Field24 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField24() string {
	if c == nil || c.Field24 == nil {
		return ""
	}
	return *c.Field24
}

// GetField25 returns the Field25 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField25() string {
	if c == nil || c.Field25 == nil {
		return ""
	}
	return *c.Field25
}

// GetField26 returns the Field26 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField26() string {
	if c == nil || c.Field26 == nil {
		return ""
	}
	return *c.Field26
}

// GetField27 returns the Field27 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField27() string {
	if c == nil || c.Field27 == nil {
		return ""
	}
	return *c.Field27
}

// GetField28 returns the Field28 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField28() string {
	if c == nil || c.Field28 == nil {
		return ""
	}
	return *c.Field28
}

// GetField29 returns the Field29 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField29() string {
	if c == nil || c.Field29 == nil {
		return ""
	}
	return *c.Field29
}

// GetField3 returns the Field3 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField3() string {
	if c == nil || c.Field3 == nil {
		return ""
	}
	return *c.Field3
}

// GetField30 returns the Field30 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField30() string {
	if c == nil || c.Field30 == nil {
		return ""
	}
	return *c.Field30
}

// GetField31 returns the Field31 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField31() string {
	if c == nil || c.Field31 == nil {
		return ""
	}
	return *c.Field31
}

// GetField32 returns the Field32 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField32() string {
	if c == nil || c.Field32 == nil {
		return ""
	}
	return *c.Field32
}

// GetField33 returns the Field33 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField33() string {
	if c == nil || c.Field33 == nil {
		return ""
	}
	return *c.Field33
}

// GetField34 returns the Field34 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField34() string {
	if c == nil || c.Field34 == nil {
		return ""
	}
	return *c.Field34
}

// GetField35 returns the Field35 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField35() string {
	if c == nil || c.Field35 == nil {
		return ""
	}
	return *c.Field35
}

// GetField36 returns the Field36 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField36() string {
	if c == nil || c.Field36 == nil {
		return ""
	}
	return *c.Field36
}

// GetField37 returns the Field37 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField37() string {
	if c == nil || c.Field37 == nil {
		return ""
	}
	return *c.Field37
}

// GetField38 returns the Field38 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField38() string {
	if c == nil || c.Field38 == nil {
		return ""
	}
	return *c.Field38
}

// GetField39 returns the Field39 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField39() string {
	if c == nil || c.Field39 == nil {
		return ""
	}
	return *c.Field39
}

// GetField4 returns the Field4 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField4() string {
	if c == nil || c.Field4 == nil {
		return ""
	}
	return *c.Field4
}

// GetField40 returns the Field40 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField40() string {
	if c == nil || c.Field40 == nil {
		return ""
	}
	return *c.Field40
}

// GetField41 returns the Field41 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField41() string {
	if c == nil || c.Field41 == nil {
		return ""
	}
	return *c.Field41
}

// GetField42 returns the Field42 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField42() string {
	if c == nil || c.Field42 == nil {
		return ""
	}
	return *c.Field42
}

// GetField43 returns the Field43 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField43() string {
	if c == nil || c.Field43 == nil {
		return ""
	}
	return *c.Field43
}

// GetField44 returns the Field44 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField44() string {
	if c == nil || c.Field44 == nil {
		return ""
	}
	return *c.Field44
}

// GetField45 returns the Field45 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField45() string {
	if c == nil || c.Field45 == nil {
		return ""
	}
	return *c.Field45
}

// GetField46 returns the Field46 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField46() string {
	if c == nil || c.Field46 == nil {
		return ""
	}
	return *c.Field46
}

// GetField47 returns the Field47 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField47() string {
	if c == nil || c.Field47 == nil {
		return ""
	}
	return *c.Field47
}

// GetField48 returns the Field48 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField48() string {
	if c == nil || c.Field48 == nil {
		return ""
	}
	return *c.Field48
}

// GetField49 returns the Field49 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField49() string {
	if c == nil || c.Field49 == nil {
		return ""
	}
	return *c.Field49
}

// GetField5 returns the Field5 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField5() string {
	if c == nil || c.Field5 == nil {
		return ""
	}
	return *c.Field5
}

// GetField50 returns the Field50 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField50() string {
	if c == nil || c.Field50 == nil {
		return ""
	}
	return *c.Field50
}

// GetField51 returns the Field51 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField51() string {
	if c == nil || c.Field51 == nil {
		return ""
	}
	return *c.Field51
}

// GetField52 returns the Field52 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField52() string {
	if c == nil || c.Field52 == nil {
		return ""
	}
	return *c.Field52
}

// GetField53 returns the Field53 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField53() string {
	if c == nil || c.Field53 == nil {
		return ""
	}
	return *c.Field53
}

// GetField54 returns the Field54 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField54() string {
	if c == nil || c.Field54 == nil {
		return ""
	}
	return *c.Field54
}

// GetField55 returns the Field55 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField55() string {
	if c == nil || c.Field55 == nil {
		return ""
	}
	return *c.Field55
}

// GetField56 returns the Field56 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField56() string {
	if c == nil || c.Field56 == nil {
		return ""
	}
	return *c.Field56
}

// GetField57 returns the Field57 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField57() string {
	if c == nil || c.Field57 == nil {
		return ""
	}
	return *c.Field57
}

// GetField58 returns the Field58 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField58() string {
	if c == nil || c.Field58 == nil {
		return ""
	}
	return *c.Field58
}

// GetField59 returns the Field59 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField59() string {
	if c == nil || c.Field59 == nil {
		return ""
	}
	return *c.Field59
}

// GetField6 returns the Field6 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField6() string {
	if c == nil || c.Field6 == nil {
		return ""
	}
	return *c.Field6
}

// GetField60 returns the Field60 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField60() string {
	if c == nil || c.Field60 == nil {
		return ""
	}
	return *c.Field60
}

// GetField61 returns the Field61 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField61() string {
	if c == nil || c.Field61 == nil {
		return ""
	}
	return *c.Field61
}

// GetField62 returns the Field62 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField62() string {
	if c == nil || c.Field62 == nil {
		return ""
	}
	return *c.Field62
}

// GetField63 returns the Field63 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField63() string {
	if c == nil || c.Field63 == nil {
		return ""
	}
	return *c.Field63
}

// GetField64 returns the Field64 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField64() string {
	if c == nil || c.Field64 == nil {
		return ""
	}
	return *c.Field64
}

// GetField65 returns the Field65 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField65() string {
	if c == nil || c.Field65 == nil {
		return ""
	}
	return *c.Field65
}

// GetField66 returns the Field66 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField66() string {
	if c == nil || c.Field66 == nil {
		return ""
	}
	return *c.Field66
}

// GetField67 returns the Field67 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField67() string {
	if c == nil || c.Field67 == nil {
		return ""
	}
	return *c.Field67
}

// GetField68 returns the Field68 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField68() string {
	if c == nil || c.Field68 == nil {
		return ""
	}
	return *c.Field68
}

// GetField69 returns the Field69 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField69() string {
	if c == nil || c.Field69 == nil {
		return ""
	}
	return *c.Field69
}

// GetField7 returns the Field7 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField7() string {
	if c == nil || c.Field7 == nil {
		return ""
	}
	return *c.Field7
}

// GetField70 returns the Field70 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField70() string {
	if c == nil || c.Field70 == nil {
		return ""
	}
	return *c.Field70
}

// GetField71 returns the Field71 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField71() string {
	if c == nil || c.Field71 == nil {
		return ""
	}
	return *c.Field71
}

// GetField72 returns the Field72 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField72() string {
	if c == nil || c.Field72 == nil {
		return ""
	}
	return *c.Field72
}

// GetField73 returns the Field73 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField73() string {
	if c == nil || c.Field73 == nil {
		return ""
	}
	return *c.Field73
}

// GetField74 returns the Field74 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField74() string {
	if c == nil || c.Field74 == nil {
		return ""
	}
	return *c.Field74
}

// GetField75 returns the Field75 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField75() string {
	if c == nil || c.Field75 == nil {
		return ""
	}
	return *c.Field75
}

// GetField76 returns the Field76 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField76() string {
	if c == nil || c.Field76 == nil {
		return ""
	}
	return *c.Field76
}

// GetField77 returns the Field77 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField77() string {
	if c == nil || c.Field77 == nil {
		return ""
	}
	return *c.Field77
}

// GetField78 returns the Field78 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField78() string {
	if c == nil || c.Field78 == nil {
		return ""
	}
	return *c.Field78
}

// GetField79 returns the Field79 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField79() string {
	if c == nil || c.Field79 == nil {
		return ""
	}
	return *c.Field79
}

// GetField8 returns the Field8 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField8() string {
	if c == nil || c.Field8 == nil {
		return ""
	}
	return *c.Field8
}

// GetField80 returns the Field80 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField80() string {
	if c == nil || c.Field80 == nil {
		return ""
	}
	return *c.Field80
}

// GetField81 returns the Field81 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField81() string {
	if c == nil || c.Field81 == nil {
		return ""
	}
	return *c.Field81
}

// GetField82 returns the Field82 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField82() string {
	if c == nil || c.Field82 == nil {
		return ""
	}
	return *c.Field82
}

// GetField83 returns the Field83 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField83() string {
	if c == nil || c.Field83 == nil {
		return ""
	}
	return *c.Field83
}

// GetField84 returns the Field84 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField84() string {
	if c == nil || c.Field84 == nil {
		return ""
	}
	return *c.Field84
}

// GetField85 returns the Field85 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField85() string {
	if c == nil || c.Field85 == nil {
		return ""
	}
	return *c.Field85
}

// GetField86 returns the Field86 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField86() string {
	if c == nil || c.Field86 == nil {
		return ""
	}
	return *c.Field86
}

// GetField87 returns the Field87 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField87() string {
	if c == nil || c.Field87 == nil {
		return ""
	}
	return *c.Field87
}

// GetField88 returns the Field88 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField88() string {
	if c == nil || c.Field88 == nil {
		return ""
	}
	return *c.Field88
}

// GetField89 returns the Field89 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField89() string {
	if c == nil || c.Field89 == nil {
		return ""
	}
	return *c.Field89
}

// GetField9 returns the Field9 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField9() string {
	if c == nil || c.Field9 == nil {
		return ""
	}
	return *c.Field9
}

// GetField90 returns the Field90 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField90() string {
	if c == nil || c.Field90 == nil {
		return ""
	}
	return *c.Field90
}

// GetField91 returns the Field91 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField91() string {
	if c == nil || c.Field91 == nil {
		return ""
	}
	return *c.Field91
}

// GetField92 returns the Field92 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField92() string {
	if c == nil || c.Field92 == nil {
		return ""
	}
	return *c.Field92
}

// GetField93 returns the Field93 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField93() string {
	if c == nil || c.Field93 == nil {
		return ""
	}
	return *c.Field93
}

// GetField94 returns the Field94 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField94() string {
	if c == nil || c.Field94 == nil {
		return ""
	}
	return *c.Field94
}

// GetField95 returns the Field95 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField95() string {
	if c == nil || c.Field95 == nil {
		return ""
	}
	return *c.Field95
}

// GetField96 returns the Field96 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField96() string {
	if c == nil || c.Field96 == nil {
		return ""
	}
	return *c.Field96
}

// GetField97 returns the Field97 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField97() string {
	if c == nil || c.Field97 == nil {
		return ""
	}
	return *c.Field97
}

// GetField98 returns the Field98 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField98() string {
	if c == nil || c.Field98 == nil {
		return ""
	}
	return *c.Field98
}

// GetField99 returns the Field99 field if it's non-nil, zero value otherwise.
func (c *CallExtensionsHolder) GetField99() string {
	if c == nil || c.Field99 == nil {
		return ""
	}
	return *c.Field99
}

// GetIsPrivate returns the IsPrivate field if it's non-nil, zero value otherwise.
func (c *CallNotesHolder) GetIsPrivate() string {
	if c == nil || c.IsPrivate == nil {
		return ""
	}
	return *c.IsPrivate
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *CallNotesHolder) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (c *CallNotesHolder) GetValue() string {
	if c == nil || c.Value == nil {
		return ""
	}
	return *c.Value
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *CallSystemCodesHolder) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (c *CallSystemCodesHolder) GetShortName() string {
	if c == nil || c.ShortName == nil {
		return ""
	}
	return *c.ShortName
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (c *ChargingTypesHolder) GetShortName() string {
	if c == nil || c.ShortName == nil {
		return ""
	}
	return *c.ShortName
}

// GetComponent returns the Component field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetComponent() string {
	if c == nil || c.Component == nil {
		return ""
	}
	return *c.Component
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetDescription() string {
	if c == nil || c.Description == nil {
		return ""
	}
	return *c.Description
}

// GetHostname returns the Hostname field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetHostname() string {
	if c == nil || c.Hostname == nil {
		return ""
	}
	return *c.Hostname
}

// GetInvNr returns the InvNr field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetInvNr() string {
	if c == nil || c.InvNr == nil {
		return ""
	}
	return *c.InvNr
}

// GetIPAddress returns the IPAddress field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetIPAddress() string {
	if c == nil || c.IPAddress == nil {
		return ""
	}
	return *c.IPAddress
}

// GetLocation returns the Location field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocation() string {
	if c == nil || c.Location == nil {
		return ""
	}
	return *c.Location
}

// GetLocationCategory returns the LocationCategory field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationCategory() string {
	if c == nil || c.LocationCategory == nil {
		return ""
	}
	return *c.LocationCategory
}

// GetLocationCity returns the LocationCity field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationCity() string {
	if c == nil || c.LocationCity == nil {
		return ""
	}
	return *c.LocationCity
}

// GetLocationCountry returns the LocationCountry field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationCountry() string {
	if c == nil || c.LocationCountry == nil {
		return ""
	}
	return *c.LocationCountry
}

// GetLocationDescription returns the LocationDescription field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationDescription() string {
	if c == nil || c.LocationDescription == nil {
		return ""
	}
	return *c.LocationDescription
}

// GetLocationLevel returns the LocationLevel field.
func (c *ComponentsHolder) GetLocationLevel() *float32 {
	if c == nil {
		return nil
	}
	return c.LocationLevel
}

// GetLocationName returns the LocationName field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationName() string {
	if c == nil || c.LocationName == nil {
		return ""
	}
	return *c.LocationName
}

// GetLocationProvince returns the LocationProvince field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationProvince() string {
	if c == nil || c.LocationProvince == nil {
		return ""
	}
	return *c.LocationProvince
}

// GetLocationRegion returns the LocationRegion field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationRegion() string {
	if c == nil || c.LocationRegion == nil {
		return ""
	}
	return *c.LocationRegion
}

// GetLocationStreet returns the LocationStreet field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationStreet() string {
	if c == nil || c.LocationStreet == nil {
		return ""
	}
	return *c.LocationStreet
}

// GetLocationTel returns the LocationTel field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationTel() string {
	if c == nil || c.LocationTel == nil {
		return ""
	}
	return *c.LocationTel
}

// GetLocationZip returns the LocationZip field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetLocationZip() string {
	if c == nil || c.LocationZip == nil {
		return ""
	}
	return *c.LocationZip
}

// GetMACAddress returns the MACAddress field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetMACAddress() string {
	if c == nil || c.MACAddress == nil {
		return ""
	}
	return *c.MACAddress
}

// GetManufacturer returns the Manufacturer field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetManufacturer() string {
	if c == nil || c.Manufacturer == nil {
		return ""
	}
	return *c.Manufacturer
}

// GetModel returns the Model field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetModel() string {
	if c == nil || c.Model == nil {
		return ""
	}
	return *c.Model
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetOpSys returns the OpSys field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetOpSys() string {
	if c == nil || c.OpSys == nil {
		return ""
	}
	return *c.OpSys
}

// GetRoom returns the Room field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetRoom() string {
	if c == nil || c.Room == nil {
		return ""
	}
	return *c.Room
}

// GetSerNr returns the SerNr field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetSerNr() string {
	if c == nil || c.SerNr == nil {
		return ""
	}
	return *c.SerNr
}

// GetSerNrProv returns the SerNrProv field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetSerNrProv() string {
	if c == nil || c.SerNrProv == nil {
		return ""
	}
	return *c.SerNrProv
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetShortName() string {
	if c == nil || c.ShortName == nil {
		return ""
	}
	return *c.ShortName
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *ComponentsHolder) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetDeactivateOutboundTriggers returns the DeactivateOutboundTriggers field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetDeactivateOutboundTriggers() string {
	if c == nil || c.DeactivateOutboundTriggers == nil {
		return ""
	}
	return *c.DeactivateOutboundTriggers
}

// GetForwardAfterClose returns the ForwardAfterClose field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetForwardAfterClose() string {
	if c == nil || c.ForwardAfterClose == nil {
		return ""
	}
	return *c.ForwardAfterClose
}

// GetMakePreSelection returns the MakePreSelection field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetMakePreSelection() string {
	if c == nil || c.MakePreSelection == nil {
		return ""
	}
	return *c.MakePreSelection
}

// GetMergeDefaultsOnContractOrContractElementChange returns the MergeDefaultsOnContractOrContractElementChange field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetMergeDefaultsOnContractOrContractElementChange() string {
	if c == nil || c.MergeDefaultsOnContractOrContractElementChange == nil {
		return ""
	}
	return *c.MergeDefaultsOnContractOrContractElementChange
}

// GetMergeLocationFromCaller returns the MergeLocationFromCaller field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetMergeLocationFromCaller() string {
	if c == nil || c.MergeLocationFromCaller == nil {
		return ""
	}
	return *c.MergeLocationFromCaller
}

// GetSetCurrentCallState returns the SetCurrentCallState field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetSetCurrentCallState() string {
	if c == nil || c.SetCurrentCallState == nil {
		return ""
	}
	return *c.SetCurrentCallState
}

// GetUpdateAfterCloseAllowed returns the UpdateAfterCloseAllowed field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetUpdateAfterCloseAllowed() string {
	if c == nil || c.UpdateAfterCloseAllowed == nil {
		return ""
	}
	return *c.UpdateAfterCloseAllowed
}

// GetUseCodeDefaults returns the UseCodeDefaults field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetUseCodeDefaults() string {
	if c == nil || c.UseCodeDefaults == nil {
		return ""
	}
	return *c.UseCodeDefaults
}

// GetUseIndependentDeviceRef returns the UseIndependentDeviceRef field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetUseIndependentDeviceRef() string {
	if c == nil || c.UseIndependentDeviceRef == nil {
		return ""
	}
	return *c.UseIndependentDeviceRef
}

// GetUsePartnerSideSuccessors returns the UsePartnerSideSuccessors field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetUsePartnerSideSuccessors() string {
	if c == nil || c.UsePartnerSideSuccessors == nil {
		return ""
	}
	return *c.UsePartnerSideSuccessors
}

// GetUseSuccessors returns the UseSuccessors field if it's non-nil, zero value otherwise.
func (c *ControlFlagsHolder) GetUseSuccessors() string {
	if c == nil || c.UseSuccessors == nil {
		return ""
	}
	return *c.UseSuccessors
}

// GetComponent returns the Component field if it's non-nil, zero value otherwise.
func (d *DeviceMovementsDeviceHolder) GetComponent() string {
	if d == nil || d.Component == nil {
		return ""
	}
	return *d.Component
}

// GetInvNr returns the InvNr field if it's non-nil, zero value otherwise.
func (d *DeviceMovementsDeviceHolder) GetInvNr() string {
	if d == nil || d.InvNr == nil {
		return ""
	}
	return *d.InvNr
}

// GetManufacturer returns the Manufacturer field if it's non-nil, zero value otherwise.
func (d *DeviceMovementsDeviceHolder) GetManufacturer() string {
	if d == nil || d.Manufacturer == nil {
		return ""
	}
	return *d.Manufacturer
}

// GetModel returns the Model field if it's non-nil, zero value otherwise.
func (d *DeviceMovementsDeviceHolder) GetModel() string {
	if d == nil || d.Model == nil {
		return ""
	}
	return *d.Model
}

// GetOwner returns the Owner field if it's non-nil, zero value otherwise.
func (d *DeviceMovementsDeviceHolder) GetOwner() string {
	if d == nil || d.Owner == nil {
		return ""
	}
	return *d.Owner
}

// GetSerNr returns the SerNr field if it's non-nil, zero value otherwise.
func (d *DeviceMovementsDeviceHolder) GetSerNr() string {
	if d == nil || d.SerNr == nil {
		return ""
	}
	return *d.SerNr
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (d *DeviceMovementsDeviceHolder) GetShortName() string {
	if d == nil || d.ShortName == nil {
		return ""
	}
	return *d.ShortName
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (d *DeviceMovementsDeviceHolder) GetType() string {
	if d == nil || d.Type == nil {
		return ""
	}
	return *d.Type
}

// GetUNSPSC returns the UNSPSC field if it's non-nil, zero value otherwise.
func (d *DeviceMovementsDeviceHolder) GetUNSPSC() string {
	if d == nil || d.UNSPSC == nil {
		return ""
	}
	return *d.UNSPSC
}

// GetDevice returns the Device field.
func (d *DeviceMovementsHolder) GetDevice() *DeviceMovementsDeviceHolder {
	if d == nil {
		return nil
	}
	return d.Device
}

// GetFromLocation returns the FromLocation field.
func (d *DeviceMovementsHolder) GetFromLocation() *LocationsHolder {
	if d == nil {
		return nil
	}
	return d.FromLocation
}

// GetToLocation returns the ToLocation field.
func (d *DeviceMovementsHolder) GetToLocation() *LocationsHolder {
	if d == nil {
		return nil
	}
	return d.ToLocation
}

// GetComponent returns the Component field if it's non-nil, zero value otherwise.
func (d *DevicesHolder) GetComponent() string {
	if d == nil || d.Component == nil {
		return ""
	}
	return *d.Component
}

// GetInvNr returns the InvNr field if it's non-nil, zero value otherwise.
func (d *DevicesHolder) GetInvNr() string {
	if d == nil || d.InvNr == nil {
		return ""
	}
	return *d.InvNr
}

// GetManufacturer returns the Manufacturer field if it's non-nil, zero value otherwise.
func (d *DevicesHolder) GetManufacturer() string {
	if d == nil || d.Manufacturer == nil {
		return ""
	}
	return *d.Manufacturer
}

// GetModel returns the Model field if it's non-nil, zero value otherwise.
func (d *DevicesHolder) GetModel() string {
	if d == nil || d.Model == nil {
		return ""
	}
	return *d.Model
}

// GetSerNr returns the SerNr field if it's non-nil, zero value otherwise.
func (d *DevicesHolder) GetSerNr() string {
	if d == nil || d.SerNr == nil {
		return ""
	}
	return *d.SerNr
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (d *DevicesHolder) GetShortName() string {
	if d == nil || d.ShortName == nil {
		return ""
	}
	return *d.ShortName
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (d *DevicesHolder) GetType() string {
	if d == nil || d.Type == nil {
		return ""
	}
	return *d.Type
}

// GetUNSPSC returns the UNSPSC field if it's non-nil, zero value otherwise.
func (d *DevicesHolder) GetUNSPSC() string {
	if d == nil || d.UNSPSC == nil {
		return ""
	}
	return *d.UNSPSC
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (e *EntityTypesHolder) GetName() string {
	if e == nil || e.Name == nil {
		return ""
	}
	return *e.Name
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (e *EntityTypesHolder) GetShortName() string {
	if e == nil || e.ShortName == nil {
		return ""
	}
	return *e.ShortName
}

// GetAddRemarksToSummary returns the AddRemarksToSummary field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetAddRemarksToSummary() string {
	if i == nil || i.AddRemarksToSummary == nil {
		return ""
	}
	return *i.AddRemarksToSummary
}

// GetCallAcknowledgeTime returns the CallAcknowledgeTime field.
func (i *InboundCallsHolder) GetCallAcknowledgeTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.CallAcknowledgeTime
}

// GetCallCloseTime returns the CallCloseTime field.
func (i *InboundCallsHolder) GetCallCloseTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.CallCloseTime
}

// GetCaller returns the Caller field.
func (i *InboundCallsHolder) GetCaller() *PersonsHolder {
	if i == nil {
		return nil
	}
	return i.Caller
}

// GetCallOpenTime returns the CallOpenTime field.
func (i *InboundCallsHolder) GetCallOpenTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.CallOpenTime
}

// GetCallRecoveryTime returns the CallRecoveryTime field.
func (i *InboundCallsHolder) GetCallRecoveryTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.CallRecoveryTime
}

// GetCallResponseTime returns the CallResponseTime field.
func (i *InboundCallsHolder) GetCallResponseTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.CallResponseTime
}

// GetCallSendTime returns the CallSendTime field.
func (i *InboundCallsHolder) GetCallSendTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.CallSendTime
}

// GetCallStartSLATime returns the CallStartSLATime field.
func (i *InboundCallsHolder) GetCallStartSLATime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.CallStartSLATime
}

// GetCCP returns the CCP field.
func (i *InboundCallsHolder) GetCCP() *PersonsHolder {
	if i == nil {
		return nil
	}
	return i.CCP
}

// GetCHD returns the CHD field.
func (i *InboundCallsHolder) GetCHD() *PersonsHolder {
	if i == nil {
		return nil
	}
	return i.CHD
}

// GetCustCallID returns the CustCallID field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustCallID() string {
	if i == nil || i.CustCallID == nil {
		return ""
	}
	return *i.CustCallID
}

// GetCustomerCategory1 returns the CustomerCategory1 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerCategory1() string {
	if i == nil || i.CustomerCategory1 == nil {
		return ""
	}
	return *i.CustomerCategory1
}

// GetCustomerCategory2 returns the CustomerCategory2 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerCategory2() string {
	if i == nil || i.CustomerCategory2 == nil {
		return ""
	}
	return *i.CustomerCategory2
}

// GetCustomerCategory3 returns the CustomerCategory3 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerCategory3() string {
	if i == nil || i.CustomerCategory3 == nil {
		return ""
	}
	return *i.CustomerCategory3
}

// GetCustomerCategory4 returns the CustomerCategory4 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerCategory4() string {
	if i == nil || i.CustomerCategory4 == nil {
		return ""
	}
	return *i.CustomerCategory4
}

// GetCustomerCategory5 returns the CustomerCategory5 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerCategory5() string {
	if i == nil || i.CustomerCategory5 == nil {
		return ""
	}
	return *i.CustomerCategory5
}

// GetCustomerReasonCategory1 returns the CustomerReasonCategory1 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerReasonCategory1() string {
	if i == nil || i.CustomerReasonCategory1 == nil {
		return ""
	}
	return *i.CustomerReasonCategory1
}

// GetCustomerReasonCategory2 returns the CustomerReasonCategory2 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerReasonCategory2() string {
	if i == nil || i.CustomerReasonCategory2 == nil {
		return ""
	}
	return *i.CustomerReasonCategory2
}

// GetCustomerReasonCategory3 returns the CustomerReasonCategory3 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerReasonCategory3() string {
	if i == nil || i.CustomerReasonCategory3 == nil {
		return ""
	}
	return *i.CustomerReasonCategory3
}

// GetCustomerReasonCategory4 returns the CustomerReasonCategory4 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerReasonCategory4() string {
	if i == nil || i.CustomerReasonCategory4 == nil {
		return ""
	}
	return *i.CustomerReasonCategory4
}

// GetCustomerReasonCategory5 returns the CustomerReasonCategory5 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetCustomerReasonCategory5() string {
	if i == nil || i.CustomerReasonCategory5 == nil {
		return ""
	}
	return *i.CustomerReasonCategory5
}

// GetCustomerRequestedEndTime returns the CustomerRequestedEndTime field.
func (i *InboundCallsHolder) GetCustomerRequestedEndTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.CustomerRequestedEndTime
}

// GetCustomerRequestedStartTime returns the CustomerRequestedStartTime field.
func (i *InboundCallsHolder) GetCustomerRequestedStartTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.CustomerRequestedStartTime
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetDescription() string {
	if i == nil || i.Description == nil {
		return ""
	}
	return *i.Description
}

// GetDiagnosis returns the Diagnosis field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetDiagnosis() string {
	if i == nil || i.Diagnosis == nil {
		return ""
	}
	return *i.Diagnosis
}

// GetMainComp returns the MainComp field.
func (i *InboundCallsHolder) GetMainComp() *ComponentsHolder {
	if i == nil {
		return nil
	}
	return i.MainComp
}

// GetNotes returns the Notes field.
func (i *InboundCallsHolder) GetNotes() *CallNotesHolder {
	if i == nil {
		return nil
	}
	return i.Notes
}

// GetOwnership returns the Ownership field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetOwnership() string {
	if i == nil || i.Ownership == nil {
		return ""
	}
	return *i.Ownership
}

// GetPartnerCoreTicketId returns the PartnerCoreTicketId field.
func (i *InboundCallsHolder) GetPartnerCoreTicketId() *float32 {
	if i == nil {
		return nil
	}
	return i.PartnerCoreTicketId
}

// GetProblemStartTime returns the ProblemStartTime field.
func (i *InboundCallsHolder) GetProblemStartTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.ProblemStartTime
}

// GetProviderCategory1 returns the ProviderCategory1 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderCategory1() string {
	if i == nil || i.ProviderCategory1 == nil {
		return ""
	}
	return *i.ProviderCategory1
}

// GetProviderCategory2 returns the ProviderCategory2 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderCategory2() string {
	if i == nil || i.ProviderCategory2 == nil {
		return ""
	}
	return *i.ProviderCategory2
}

// GetProviderCategory3 returns the ProviderCategory3 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderCategory3() string {
	if i == nil || i.ProviderCategory3 == nil {
		return ""
	}
	return *i.ProviderCategory3
}

// GetProviderCategory4 returns the ProviderCategory4 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderCategory4() string {
	if i == nil || i.ProviderCategory4 == nil {
		return ""
	}
	return *i.ProviderCategory4
}

// GetProviderCategory5 returns the ProviderCategory5 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderCategory5() string {
	if i == nil || i.ProviderCategory5 == nil {
		return ""
	}
	return *i.ProviderCategory5
}

// GetProviderReasonCategory1 returns the ProviderReasonCategory1 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderReasonCategory1() string {
	if i == nil || i.ProviderReasonCategory1 == nil {
		return ""
	}
	return *i.ProviderReasonCategory1
}

// GetProviderReasonCategory2 returns the ProviderReasonCategory2 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderReasonCategory2() string {
	if i == nil || i.ProviderReasonCategory2 == nil {
		return ""
	}
	return *i.ProviderReasonCategory2
}

// GetProviderReasonCategory3 returns the ProviderReasonCategory3 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderReasonCategory3() string {
	if i == nil || i.ProviderReasonCategory3 == nil {
		return ""
	}
	return *i.ProviderReasonCategory3
}

// GetProviderReasonCategory4 returns the ProviderReasonCategory4 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderReasonCategory4() string {
	if i == nil || i.ProviderReasonCategory4 == nil {
		return ""
	}
	return *i.ProviderReasonCategory4
}

// GetProviderReasonCategory5 returns the ProviderReasonCategory5 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetProviderReasonCategory5() string {
	if i == nil || i.ProviderReasonCategory5 == nil {
		return ""
	}
	return *i.ProviderReasonCategory5
}

// GetProviderScheduledEndTime returns the ProviderScheduledEndTime field.
func (i *InboundCallsHolder) GetProviderScheduledEndTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.ProviderScheduledEndTime
}

// GetProviderScheduledStartTime returns the ProviderScheduledStartTime field.
func (i *InboundCallsHolder) GetProviderScheduledStartTime() *CiscoDateTime {
	if i == nil {
		return nil
	}
	return i.ProviderScheduledStartTime
}

// GetRemarks returns the Remarks field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetRemarks() string {
	if i == nil || i.Remarks == nil {
		return ""
	}
	return *i.Remarks
}

// GetSDCallID returns the SDCallID field.
func (i *InboundCallsHolder) GetSDCallID() *float32 {
	if i == nil {
		return nil
	}
	return i.SDCallID
}

// GetShortDescription returns the ShortDescription field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetShortDescription() string {
	if i == nil || i.ShortDescription == nil {
		return ""
	}
	return *i.ShortDescription
}

// GetSolution returns the Solution field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSolution() string {
	if i == nil || i.Solution == nil {
		return ""
	}
	return *i.Solution
}

// GetSPCallID returns the SPCallID field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSPCallID() string {
	if i == nil || i.SPCallID == nil {
		return ""
	}
	return *i.SPCallID
}

// GetSubComp returns the SubComp field.
func (i *InboundCallsHolder) GetSubComp() *ComponentsHolder {
	if i == nil {
		return nil
	}
	return i.SubComp
}

// GetSysSpecField1 returns the SysSpecField1 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField1() string {
	if i == nil || i.SysSpecField1 == nil {
		return ""
	}
	return *i.SysSpecField1
}

// GetSysSpecField10 returns the SysSpecField10 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField10() string {
	if i == nil || i.SysSpecField10 == nil {
		return ""
	}
	return *i.SysSpecField10
}

// GetSysSpecField2 returns the SysSpecField2 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField2() string {
	if i == nil || i.SysSpecField2 == nil {
		return ""
	}
	return *i.SysSpecField2
}

// GetSysSpecField3 returns the SysSpecField3 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField3() string {
	if i == nil || i.SysSpecField3 == nil {
		return ""
	}
	return *i.SysSpecField3
}

// GetSysSpecField4 returns the SysSpecField4 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField4() string {
	if i == nil || i.SysSpecField4 == nil {
		return ""
	}
	return *i.SysSpecField4
}

// GetSysSpecField5 returns the SysSpecField5 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField5() string {
	if i == nil || i.SysSpecField5 == nil {
		return ""
	}
	return *i.SysSpecField5
}

// GetSysSpecField6 returns the SysSpecField6 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField6() string {
	if i == nil || i.SysSpecField6 == nil {
		return ""
	}
	return *i.SysSpecField6
}

// GetSysSpecField7 returns the SysSpecField7 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField7() string {
	if i == nil || i.SysSpecField7 == nil {
		return ""
	}
	return *i.SysSpecField7
}

// GetSysSpecField8 returns the SysSpecField8 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField8() string {
	if i == nil || i.SysSpecField8 == nil {
		return ""
	}
	return *i.SysSpecField8
}

// GetSysSpecField9 returns the SysSpecField9 field if it's non-nil, zero value otherwise.
func (i *InboundCallsHolder) GetSysSpecField9() string {
	if i == nil || i.SysSpecField9 == nil {
		return ""
	}
	return *i.SysSpecField9
}

// GetCompLocation returns the CompLocation field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetCompLocation() string {
	if i == nil || i.CompLocation == nil {
		return ""
	}
	return *i.CompLocation
}

// GetComponent returns the Component field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetComponent() string {
	if i == nil || i.Component == nil {
		return ""
	}
	return *i.Component
}

// GetContractIDCust returns the ContractIDCust field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetContractIDCust() string {
	if i == nil || i.ContractIDCust == nil {
		return ""
	}
	return *i.ContractIDCust
}

// GetContractIDProv returns the ContractIDProv field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetContractIDProv() string {
	if i == nil || i.ContractIDProv == nil {
		return ""
	}
	return *i.ContractIDProv
}

// GetCustomerCategory1 returns the CustomerCategory1 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetCustomerCategory1() string {
	if i == nil || i.CustomerCategory1 == nil {
		return ""
	}
	return *i.CustomerCategory1
}

// GetCustomerCategory2 returns the CustomerCategory2 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetCustomerCategory2() string {
	if i == nil || i.CustomerCategory2 == nil {
		return ""
	}
	return *i.CustomerCategory2
}

// GetCustomerCategory3 returns the CustomerCategory3 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetCustomerCategory3() string {
	if i == nil || i.CustomerCategory3 == nil {
		return ""
	}
	return *i.CustomerCategory3
}

// GetCustomerCategory4 returns the CustomerCategory4 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetCustomerCategory4() string {
	if i == nil || i.CustomerCategory4 == nil {
		return ""
	}
	return *i.CustomerCategory4
}

// GetCustomerCategory5 returns the CustomerCategory5 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetCustomerCategory5() string {
	if i == nil || i.CustomerCategory5 == nil {
		return ""
	}
	return *i.CustomerCategory5
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetName() string {
	if i == nil || i.Name == nil {
		return ""
	}
	return *i.Name
}

// GetNewName returns the NewName field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetNewName() string {
	if i == nil || i.NewName == nil {
		return ""
	}
	return *i.NewName
}

// GetNewShortName returns the NewShortName field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetNewShortName() string {
	if i == nil || i.NewShortName == nil {
		return ""
	}
	return *i.NewShortName
}

// GetProviderCategory1 returns the ProviderCategory1 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetProviderCategory1() string {
	if i == nil || i.ProviderCategory1 == nil {
		return ""
	}
	return *i.ProviderCategory1
}

// GetProviderCategory2 returns the ProviderCategory2 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetProviderCategory2() string {
	if i == nil || i.ProviderCategory2 == nil {
		return ""
	}
	return *i.ProviderCategory2
}

// GetProviderCategory3 returns the ProviderCategory3 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetProviderCategory3() string {
	if i == nil || i.ProviderCategory3 == nil {
		return ""
	}
	return *i.ProviderCategory3
}

// GetProviderCategory4 returns the ProviderCategory4 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetProviderCategory4() string {
	if i == nil || i.ProviderCategory4 == nil {
		return ""
	}
	return *i.ProviderCategory4
}

// GetProviderCategory5 returns the ProviderCategory5 field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetProviderCategory5() string {
	if i == nil || i.ProviderCategory5 == nil {
		return ""
	}
	return *i.ProviderCategory5
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (i *InboundContractElementsHolder) GetShortName() string {
	if i == nil || i.ShortName == nil {
		return ""
	}
	return *i.ShortName
}

// GetBPartnerShortNameCust returns the BPartnerShortNameCust field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetBPartnerShortNameCust() string {
	if i == nil || i.BPartnerShortNameCust == nil {
		return ""
	}
	return *i.BPartnerShortNameCust
}

// GetBPartnerShortNameProv returns the BPartnerShortNameProv field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetBPartnerShortNameProv() string {
	if i == nil || i.BPartnerShortNameProv == nil {
		return ""
	}
	return *i.BPartnerShortNameProv
}

// GetBPOrganizationShortNameCust returns the BPOrganizationShortNameCust field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetBPOrganizationShortNameCust() string {
	if i == nil || i.BPOrganizationShortNameCust == nil {
		return ""
	}
	return *i.BPOrganizationShortNameCust
}

// GetBPOrganizationShortNameProv returns the BPOrganizationShortNameProv field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetBPOrganizationShortNameProv() string {
	if i == nil || i.BPOrganizationShortNameProv == nil {
		return ""
	}
	return *i.BPOrganizationShortNameProv
}

// GetContractIDCust returns the ContractIDCust field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetContractIDCust() string {
	if i == nil || i.ContractIDCust == nil {
		return ""
	}
	return *i.ContractIDCust
}

// GetContractIDProv returns the ContractIDProv field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetContractIDProv() string {
	if i == nil || i.ContractIDProv == nil {
		return ""
	}
	return *i.ContractIDProv
}

// GetCustIDProv returns the CustIDProv field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetCustIDProv() string {
	if i == nil || i.CustIDProv == nil {
		return ""
	}
	return *i.CustIDProv
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetName() string {
	if i == nil || i.Name == nil {
		return ""
	}
	return *i.Name
}

// GetNewName returns the NewName field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetNewName() string {
	if i == nil || i.NewName == nil {
		return ""
	}
	return *i.NewName
}

// GetNewShortName returns the NewShortName field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetNewShortName() string {
	if i == nil || i.NewShortName == nil {
		return ""
	}
	return *i.NewShortName
}

// GetProvIDCust returns the ProvIDCust field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetProvIDCust() string {
	if i == nil || i.ProvIDCust == nil {
		return ""
	}
	return *i.ProvIDCust
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (i *InboundContractsHolder) GetShortName() string {
	if i == nil || i.ShortName == nil {
		return ""
	}
	return *i.ShortName
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (i *IntegerKeyField) GetKey() string {
	if i == nil || i.Key == nil {
		return ""
	}
	return *i.Key
}

// GetValue returns the Value field.
func (i *IntegerKeyField) GetValue() *int32 {
	if i == nil {
		return nil
	}
	return i.Value
}

// GetLimit returns the Limit field if it's non-nil, zero value otherwise.
func (l *ListParams) GetLimit() int64 {
	if l == nil || l.Limit == nil {
		return 0
	}
	return *l.Limit
}

// GetMaxId returns the MaxId field if it's non-nil, zero value otherwise.
func (l *ListParams) GetMaxId() int64 {
	if l == nil || l.MaxId == nil {
		return 0
	}
	return *l.MaxId
}

// GetSinceId returns the SinceId field if it's non-nil, zero value otherwise.
func (l *ListParams) GetSinceId() int64 {
	if l == nil || l.SinceId == nil {
		return 0
	}
	return *l.SinceId
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (l *LocationsHolder) GetShortName() string {
	if l == nil || l.ShortName == nil {
		return ""
	}
	return *l.ShortName
}

// GetCustCallID returns the CustCallID field if it's non-nil, zero value otherwise.
func (p *ParentCallsHolder) GetCustCallID() string {
	if p == nil || p.CustCallID == nil {
		return ""
	}
	return *p.CustCallID
}

// GetSDCallID returns the SDCallID field.
func (p *ParentCallsHolder) GetSDCallID() *float32 {
	if p == nil {
		return nil
	}
	return p.SDCallID
}

// GetSPCallID returns the SPCallID field if it's non-nil, zero value otherwise.
func (p *ParentCallsHolder) GetSPCallID() string {
	if p == nil || p.SPCallID == nil {
		return ""
	}
	return *p.SPCallID
}

// GetCategory returns the Category field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetCategory() string {
	if p == nil || p.Category == nil {
		return ""
	}
	return *p.Category
}

// GetDepartment returns the Department field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetDepartment() string {
	if p == nil || p.Department == nil {
		return ""
	}
	return *p.Department
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetDescription() string {
	if p == nil || p.Description == nil {
		return ""
	}
	return *p.Description
}

// GetEMail returns the EMail field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetEMail() string {
	if p == nil || p.EMail == nil {
		return ""
	}
	return *p.EMail
}

// GetFax returns the Fax field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetFax() string {
	if p == nil || p.Fax == nil {
		return ""
	}
	return *p.Fax
}

// GetFirstName returns the FirstName field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetFirstName() string {
	if p == nil || p.FirstName == nil {
		return ""
	}
	return *p.FirstName
}

// GetLanguage returns the Language field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetLanguage() string {
	if p == nil || p.Language == nil {
		return ""
	}
	return *p.Language
}

// GetLastName returns the LastName field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetLastName() string {
	if p == nil || p.LastName == nil {
		return ""
	}
	return *p.LastName
}

// GetLocation returns the Location field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetLocation() string {
	if p == nil || p.Location == nil {
		return ""
	}
	return *p.Location
}

// GetLocationCity returns the LocationCity field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetLocationCity() string {
	if p == nil || p.LocationCity == nil {
		return ""
	}
	return *p.LocationCity
}

// GetLocationCountry returns the LocationCountry field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetLocationCountry() string {
	if p == nil || p.LocationCountry == nil {
		return ""
	}
	return *p.LocationCountry
}

// GetLocationProvince returns the LocationProvince field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetLocationProvince() string {
	if p == nil || p.LocationProvince == nil {
		return ""
	}
	return *p.LocationProvince
}

// GetLocationStreet returns the LocationStreet field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetLocationStreet() string {
	if p == nil || p.LocationStreet == nil {
		return ""
	}
	return *p.LocationStreet
}

// GetLocationZip returns the LocationZip field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetLocationZip() string {
	if p == nil || p.LocationZip == nil {
		return ""
	}
	return *p.LocationZip
}

// GetMobileTel returns the MobileTel field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetMobileTel() string {
	if p == nil || p.MobileTel == nil {
		return ""
	}
	return *p.MobileTel
}

// GetPIN returns the PIN field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetPIN() string {
	if p == nil || p.PIN == nil {
		return ""
	}
	return *p.PIN
}

// GetRoom returns the Room field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetRoom() string {
	if p == nil || p.Room == nil {
		return ""
	}
	return *p.Room
}

// GetSalutation returns the Salutation field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetSalutation() string {
	if p == nil || p.Salutation == nil {
		return ""
	}
	return *p.Salutation
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetShortName() string {
	if p == nil || p.ShortName == nil {
		return ""
	}
	return *p.ShortName
}

// GetSign returns the Sign field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetSign() string {
	if p == nil || p.Sign == nil {
		return ""
	}
	return *p.Sign
}

// GetTel returns the Tel field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetTel() string {
	if p == nil || p.Tel == nil {
		return ""
	}
	return *p.Tel
}

// GetTel2 returns the Tel2 field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetTel2() string {
	if p == nil || p.Tel2 == nil {
		return ""
	}
	return *p.Tel2
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (p *PersonsHolder) GetTitle() string {
	if p == nil || p.Title == nil {
		return ""
	}
	return *p.Title
}

// GetShortName returns the ShortName field if it's non-nil, zero value otherwise.
func (q *QueuesHolder) GetShortName() string {
	if q == nil || q.ShortName == nil {
		return ""
	}
	return *q.ShortName
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (s *StringKeyField) GetKey() string {
	if s == nil || s.Key == nil {
		return ""
	}
	return *s.Key
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (s *StringKeyField) GetValue() string {
	if s == nil || s.Value == nil {
		return ""
	}
	return *s.Value
}

// GetChangeFlag returns the ChangeFlag field if it's non-nil, zero value otherwise.
func (t *TspCode) GetChangeFlag() string {
	if t == nil || t.ChangeFlag == nil {
		return ""
	}
	return *t.ChangeFlag
}

// GetEditTimeUtc returns the EditTimeUtc field if it's non-nil, zero value otherwise.
func (t *TspCode) GetEditTimeUtc() string {
	if t == nil || t.EditTimeUtc == nil {
		return ""
	}
	return *t.EditTimeUtc
}

// GetId returns the Id field.
func (t *TspCode) GetId() *int32 {
	if t == nil {
		return nil
	}
	return t.Id
}

// GetProblemCodeDescription returns the ProblemCodeDescription field if it's non-nil, zero value otherwise.
func (t *TspCode) GetProblemCodeDescription() string {
	if t == nil || t.ProblemCodeDescription == nil {
		return ""
	}
	return *t.ProblemCodeDescription
}

// GetProblemCodeName returns the ProblemCodeName field if it's non-nil, zero value otherwise.
func (t *TspCode) GetProblemCodeName() string {
	if t == nil || t.ProblemCodeName == nil {
		return ""
	}
	return *t.ProblemCodeName
}

// GetSubTechId returns the SubTechId field.
func (t *TspCode) GetSubTechId() *int32 {
	if t == nil {
		return nil
	}
	return t.SubTechId
}

// GetSubTechName returns the SubTechName field if it's non-nil, zero value otherwise.
func (t *TspCode) GetSubTechName() string {
	if t == nil || t.SubTechName == nil {
		return ""
	}
	return *t.SubTechName
}

// GetTechId returns the TechId field.
func (t *TspCode) GetTechId() *int32 {
	if t == nil {
		return nil
	}
	return t.TechId
}

// GetTechName returns the TechName field if it's non-nil, zero value otherwise.
func (t *TspCode) GetTechName() string {
	if t == nil || t.TechName == nil {
		return ""
	}
	return *t.TechName
}
