// Copyright 2021 The go-planhat AUTHORS. All rights reserved.
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package ciscosmartbonding

import "testing"

func TestAttachmentsHolder_GetDataBase64(tt *testing.T) {
	var zeroValue string
	a := &AttachmentsHolder{DataBase64: &zeroValue}
	a.GetDataBase64()
	a = &AttachmentsHolder{}
	a.GetDataBase64()
	a = nil
	a.GetDataBase64()
}

func TestAttachmentsHolder_GetFileName(tt *testing.T) {
	var zeroValue string
	a := &AttachmentsHolder{FileName: &zeroValue}
	a.GetFileName()
	a = &AttachmentsHolder{}
	a.GetFileName()
	a = nil
	a.GetFileName()
}

func TestAttachmentsHolder_GetNR(tt *testing.T) {
	var zeroValue float32
	a := &AttachmentsHolder{NR: &zeroValue}
	a.GetNR()
	a = &AttachmentsHolder{}
	a.GetNR()
	a = nil
	a.GetNR()
}

func TestCallActivitiesHolder_GetActivityType(tt *testing.T) {
	c := &CallActivitiesHolder{}
	c.GetActivityType()
	c = nil
	c.GetActivityType()
}

func TestCallActivitiesHolder_GetBackTime(tt *testing.T) {
	c := &CallActivitiesHolder{}
	c.GetBackTime()
	c = nil
	c.GetBackTime()
}

func TestCallActivitiesHolder_GetBPPShortName(tt *testing.T) {
	var zeroValue string
	c := &CallActivitiesHolder{BPPShortName: &zeroValue}
	c.GetBPPShortName()
	c = &CallActivitiesHolder{}
	c.GetBPPShortName()
	c = nil
	c.GetBPPShortName()
}

func TestCallActivitiesHolder_GetBusyTime(tt *testing.T) {
	c := &CallActivitiesHolder{}
	c.GetBusyTime()
	c = nil
	c.GetBusyTime()
}

func TestCallActivitiesHolder_GetDistance(tt *testing.T) {
	c := &CallActivitiesHolder{}
	c.GetDistance()
	c = nil
	c.GetDistance()
}

func TestCallActivitiesHolder_GetTravelBackMinutes(tt *testing.T) {
	c := &CallActivitiesHolder{}
	c.GetTravelBackMinutes()
	c = nil
	c.GetTravelBackMinutes()
}

func TestCallActivitiesHolder_GetTravelBackRemarks(tt *testing.T) {
	var zeroValue string
	c := &CallActivitiesHolder{TravelBackRemarks: &zeroValue}
	c.GetTravelBackRemarks()
	c = &CallActivitiesHolder{}
	c.GetTravelBackRemarks()
	c = nil
	c.GetTravelBackRemarks()
}

func TestCallActivitiesHolder_GetTravelMinutes(tt *testing.T) {
	c := &CallActivitiesHolder{}
	c.GetTravelMinutes()
	c = nil
	c.GetTravelMinutes()
}

func TestCallActivitiesHolder_GetTravelRemarks(tt *testing.T) {
	var zeroValue string
	c := &CallActivitiesHolder{TravelRemarks: &zeroValue}
	c.GetTravelRemarks()
	c = &CallActivitiesHolder{}
	c.GetTravelRemarks()
	c = nil
	c.GetTravelRemarks()
}

func TestCallActivitiesHolder_GetWorkEndTime(tt *testing.T) {
	c := &CallActivitiesHolder{}
	c.GetWorkEndTime()
	c = nil
	c.GetWorkEndTime()
}

func TestCallActivitiesHolder_GetWorkMinutes(tt *testing.T) {
	c := &CallActivitiesHolder{}
	c.GetWorkMinutes()
	c = nil
	c.GetWorkMinutes()
}

func TestCallActivitiesHolder_GetWorkRemarks(tt *testing.T) {
	var zeroValue string
	c := &CallActivitiesHolder{WorkRemarks: &zeroValue}
	c.GetWorkRemarks()
	c = &CallActivitiesHolder{}
	c.GetWorkRemarks()
	c = nil
	c.GetWorkRemarks()
}

func TestCallActivitiesHolder_GetWorkStartTime(tt *testing.T) {
	c := &CallActivitiesHolder{}
	c.GetWorkStartTime()
	c = nil
	c.GetWorkStartTime()
}

func TestCallAdditionalsHolder_GetField1(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField1()
	c = nil
	c.GetField1()
}

func TestCallAdditionalsHolder_GetField10(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField10()
	c = nil
	c.GetField10()
}

func TestCallAdditionalsHolder_GetField11(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField11()
	c = nil
	c.GetField11()
}

func TestCallAdditionalsHolder_GetField12(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField12()
	c = nil
	c.GetField12()
}

func TestCallAdditionalsHolder_GetField13(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField13()
	c = nil
	c.GetField13()
}

func TestCallAdditionalsHolder_GetField14(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField14()
	c = nil
	c.GetField14()
}

func TestCallAdditionalsHolder_GetField15(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField15()
	c = nil
	c.GetField15()
}

func TestCallAdditionalsHolder_GetField16(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField16()
	c = nil
	c.GetField16()
}

func TestCallAdditionalsHolder_GetField17(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField17()
	c = nil
	c.GetField17()
}

func TestCallAdditionalsHolder_GetField18(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField18()
	c = nil
	c.GetField18()
}

func TestCallAdditionalsHolder_GetField19(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField19()
	c = nil
	c.GetField19()
}

func TestCallAdditionalsHolder_GetField2(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField2()
	c = nil
	c.GetField2()
}

func TestCallAdditionalsHolder_GetField20(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField20()
	c = nil
	c.GetField20()
}

func TestCallAdditionalsHolder_GetField21(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField21()
	c = nil
	c.GetField21()
}

func TestCallAdditionalsHolder_GetField22(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField22()
	c = nil
	c.GetField22()
}

func TestCallAdditionalsHolder_GetField23(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField23()
	c = nil
	c.GetField23()
}

func TestCallAdditionalsHolder_GetField24(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField24()
	c = nil
	c.GetField24()
}

func TestCallAdditionalsHolder_GetField25(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField25()
	c = nil
	c.GetField25()
}

func TestCallAdditionalsHolder_GetField26(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField26()
	c = nil
	c.GetField26()
}

func TestCallAdditionalsHolder_GetField27(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField27()
	c = nil
	c.GetField27()
}

func TestCallAdditionalsHolder_GetField28(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField28()
	c = nil
	c.GetField28()
}

func TestCallAdditionalsHolder_GetField29(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField29()
	c = nil
	c.GetField29()
}

func TestCallAdditionalsHolder_GetField3(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField3()
	c = nil
	c.GetField3()
}

func TestCallAdditionalsHolder_GetField30(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField30()
	c = nil
	c.GetField30()
}

func TestCallAdditionalsHolder_GetField31(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField31()
	c = nil
	c.GetField31()
}

func TestCallAdditionalsHolder_GetField32(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField32()
	c = nil
	c.GetField32()
}

func TestCallAdditionalsHolder_GetField33(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField33()
	c = nil
	c.GetField33()
}

func TestCallAdditionalsHolder_GetField34(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField34()
	c = nil
	c.GetField34()
}

func TestCallAdditionalsHolder_GetField35(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField35()
	c = nil
	c.GetField35()
}

func TestCallAdditionalsHolder_GetField36(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField36()
	c = nil
	c.GetField36()
}

func TestCallAdditionalsHolder_GetField37(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField37()
	c = nil
	c.GetField37()
}

func TestCallAdditionalsHolder_GetField38(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField38()
	c = nil
	c.GetField38()
}

func TestCallAdditionalsHolder_GetField39(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField39()
	c = nil
	c.GetField39()
}

func TestCallAdditionalsHolder_GetField4(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField4()
	c = nil
	c.GetField4()
}

func TestCallAdditionalsHolder_GetField40(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField40()
	c = nil
	c.GetField40()
}

func TestCallAdditionalsHolder_GetField41(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField41()
	c = nil
	c.GetField41()
}

func TestCallAdditionalsHolder_GetField42(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField42()
	c = nil
	c.GetField42()
}

func TestCallAdditionalsHolder_GetField43(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField43()
	c = nil
	c.GetField43()
}

func TestCallAdditionalsHolder_GetField44(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField44()
	c = nil
	c.GetField44()
}

func TestCallAdditionalsHolder_GetField45(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField45()
	c = nil
	c.GetField45()
}

func TestCallAdditionalsHolder_GetField46(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField46()
	c = nil
	c.GetField46()
}

func TestCallAdditionalsHolder_GetField47(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField47()
	c = nil
	c.GetField47()
}

func TestCallAdditionalsHolder_GetField48(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField48()
	c = nil
	c.GetField48()
}

func TestCallAdditionalsHolder_GetField49(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField49()
	c = nil
	c.GetField49()
}

func TestCallAdditionalsHolder_GetField5(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField5()
	c = nil
	c.GetField5()
}

func TestCallAdditionalsHolder_GetField50(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField50()
	c = nil
	c.GetField50()
}

func TestCallAdditionalsHolder_GetField51(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField51()
	c = nil
	c.GetField51()
}

func TestCallAdditionalsHolder_GetField52(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField52()
	c = nil
	c.GetField52()
}

func TestCallAdditionalsHolder_GetField53(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField53()
	c = nil
	c.GetField53()
}

func TestCallAdditionalsHolder_GetField54(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField54()
	c = nil
	c.GetField54()
}

func TestCallAdditionalsHolder_GetField55(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField55()
	c = nil
	c.GetField55()
}

func TestCallAdditionalsHolder_GetField56(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField56()
	c = nil
	c.GetField56()
}

func TestCallAdditionalsHolder_GetField57(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField57()
	c = nil
	c.GetField57()
}

func TestCallAdditionalsHolder_GetField58(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField58()
	c = nil
	c.GetField58()
}

func TestCallAdditionalsHolder_GetField59(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField59()
	c = nil
	c.GetField59()
}

func TestCallAdditionalsHolder_GetField6(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField6()
	c = nil
	c.GetField6()
}

func TestCallAdditionalsHolder_GetField60(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField60()
	c = nil
	c.GetField60()
}

func TestCallAdditionalsHolder_GetField61(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField61()
	c = nil
	c.GetField61()
}

func TestCallAdditionalsHolder_GetField62(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField62()
	c = nil
	c.GetField62()
}

func TestCallAdditionalsHolder_GetField63(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField63()
	c = nil
	c.GetField63()
}

func TestCallAdditionalsHolder_GetField64(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField64()
	c = nil
	c.GetField64()
}

func TestCallAdditionalsHolder_GetField7(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField7()
	c = nil
	c.GetField7()
}

func TestCallAdditionalsHolder_GetField8(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField8()
	c = nil
	c.GetField8()
}

func TestCallAdditionalsHolder_GetField9(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetField9()
	c = nil
	c.GetField9()
}

func TestCallAdditionalsHolder_GetFunctionPort(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetFunctionPort()
	c = nil
	c.GetFunctionPort()
}

func TestCallAdditionalsHolder_GetPosNr(tt *testing.T) {
	c := &CallAdditionalsHolder{}
	c.GetPosNr()
	c = nil
	c.GetPosNr()
}

func TestCallAdditionalsHolder_GetUrl1(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{Url1: &zeroValue}
	c.GetUrl1()
	c = &CallAdditionalsHolder{}
	c.GetUrl1()
	c = nil
	c.GetUrl1()
}

func TestCallAdditionalsHolder_GetUrl2(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{Url2: &zeroValue}
	c.GetUrl2()
	c = &CallAdditionalsHolder{}
	c.GetUrl2()
	c = nil
	c.GetUrl2()
}

func TestCallAdditionalsHolder_GetUrl3(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{Url3: &zeroValue}
	c.GetUrl3()
	c = &CallAdditionalsHolder{}
	c.GetUrl3()
	c = nil
	c.GetUrl3()
}

func TestCallAdditionalsHolder_GetUrl4(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{Url4: &zeroValue}
	c.GetUrl4()
	c = &CallAdditionalsHolder{}
	c.GetUrl4()
	c = nil
	c.GetUrl4()
}

func TestCallAdditionalsHolder_GetUrl5(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{Url5: &zeroValue}
	c.GetUrl5()
	c = &CallAdditionalsHolder{}
	c.GetUrl5()
	c = nil
	c.GetUrl5()
}

func TestCallAdditionalsHolder_GetUrl6(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{Url6: &zeroValue}
	c.GetUrl6()
	c = &CallAdditionalsHolder{}
	c.GetUrl6()
	c = nil
	c.GetUrl6()
}

func TestCallAdditionalsHolder_GetUrl7(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{Url7: &zeroValue}
	c.GetUrl7()
	c = &CallAdditionalsHolder{}
	c.GetUrl7()
	c = nil
	c.GetUrl7()
}

func TestCallAdditionalsHolder_GetUrl8(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{Url8: &zeroValue}
	c.GetUrl8()
	c = &CallAdditionalsHolder{}
	c.GetUrl8()
	c = nil
	c.GetUrl8()
}

func TestCallAdditionalsHolder_GetUrlName1(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{UrlName1: &zeroValue}
	c.GetUrlName1()
	c = &CallAdditionalsHolder{}
	c.GetUrlName1()
	c = nil
	c.GetUrlName1()
}

func TestCallAdditionalsHolder_GetUrlName2(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{UrlName2: &zeroValue}
	c.GetUrlName2()
	c = &CallAdditionalsHolder{}
	c.GetUrlName2()
	c = nil
	c.GetUrlName2()
}

func TestCallAdditionalsHolder_GetUrlName3(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{UrlName3: &zeroValue}
	c.GetUrlName3()
	c = &CallAdditionalsHolder{}
	c.GetUrlName3()
	c = nil
	c.GetUrlName3()
}

func TestCallAdditionalsHolder_GetUrlName4(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{UrlName4: &zeroValue}
	c.GetUrlName4()
	c = &CallAdditionalsHolder{}
	c.GetUrlName4()
	c = nil
	c.GetUrlName4()
}

func TestCallAdditionalsHolder_GetUrlName5(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{UrlName5: &zeroValue}
	c.GetUrlName5()
	c = &CallAdditionalsHolder{}
	c.GetUrlName5()
	c = nil
	c.GetUrlName5()
}

func TestCallAdditionalsHolder_GetUrlName6(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{UrlName6: &zeroValue}
	c.GetUrlName6()
	c = &CallAdditionalsHolder{}
	c.GetUrlName6()
	c = nil
	c.GetUrlName6()
}

func TestCallAdditionalsHolder_GetUrlName7(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{UrlName7: &zeroValue}
	c.GetUrlName7()
	c = &CallAdditionalsHolder{}
	c.GetUrlName7()
	c = nil
	c.GetUrlName7()
}

func TestCallAdditionalsHolder_GetUrlName8(tt *testing.T) {
	var zeroValue string
	c := &CallAdditionalsHolder{UrlName8: &zeroValue}
	c.GetUrlName8()
	c = &CallAdditionalsHolder{}
	c.GetUrlName8()
	c = nil
	c.GetUrlName8()
}

func TestCallCalculationsHolder_GetChargingTypes(tt *testing.T) {
	c := &CallCalculationsHolder{}
	c.GetChargingTypes()
	c = nil
	c.GetChargingTypes()
}

func TestCallCalculationsHolder_GetContractShortName(tt *testing.T) {
	var zeroValue string
	c := &CallCalculationsHolder{ContractShortName: &zeroValue}
	c.GetContractShortName()
	c = &CallCalculationsHolder{}
	c.GetContractShortName()
	c = nil
	c.GetContractShortName()
}

func TestCallCalculationsHolder_GetRequestedWorkEndTime(tt *testing.T) {
	c := &CallCalculationsHolder{}
	c.GetRequestedWorkEndTime()
	c = nil
	c.GetRequestedWorkEndTime()
}

func TestCallCalculationsHolder_GetRevenue(tt *testing.T) {
	var zeroValue float32
	c := &CallCalculationsHolder{Revenue: &zeroValue}
	c.GetRevenue()
	c = &CallCalculationsHolder{}
	c.GetRevenue()
	c = nil
	c.GetRevenue()
}

func TestCallCalculationsHolder_GetServiceType(tt *testing.T) {
	var zeroValue string
	c := &CallCalculationsHolder{ServiceType: &zeroValue}
	c.GetServiceType()
	c = &CallCalculationsHolder{}
	c.GetServiceType()
	c = nil
	c.GetServiceType()
}

func TestCallData_GetAttachments(tt *testing.T) {
	var zeroValue []AttachmentsHolder
	c := &CallData{Attachments: &zeroValue}
	c.GetAttachments()
	c = &CallData{}
	c.GetAttachments()
	c = nil
	c.GetAttachments()
}

func TestCallData_GetCallActivities(tt *testing.T) {
	var zeroValue []CallActivitiesHolder
	c := &CallData{CallActivities: &zeroValue}
	c.GetCallActivities()
	c = &CallData{}
	c.GetCallActivities()
	c = nil
	c.GetCallActivities()
}

func TestCallData_GetCallAdditionals(tt *testing.T) {
	var zeroValue []CallAdditionalsHolder
	c := &CallData{CallAdditionals: &zeroValue}
	c.GetCallAdditionals()
	c = &CallData{}
	c.GetCallAdditionals()
	c = nil
	c.GetCallAdditionals()
}

func TestCallData_GetCallCalculations(tt *testing.T) {
	c := &CallData{}
	c.GetCallCalculations()
	c = nil
	c.GetCallCalculations()
}

func TestCallData_GetCalls(tt *testing.T) {
	c := &CallData{}
	c.GetCalls()
	c = nil
	c.GetCalls()
}

func TestCallData_GetCallStates(tt *testing.T) {
	c := &CallData{}
	c.GetCallStates()
	c = nil
	c.GetCallStates()
}

func TestCallData_GetCallStatesSPR(tt *testing.T) {
	c := &CallData{}
	c.GetCallStatesSPR()
	c = nil
	c.GetCallStatesSPR()
}

func TestCallData_GetContractElements(tt *testing.T) {
	c := &CallData{}
	c.GetContractElements()
	c = nil
	c.GetContractElements()
}

func TestCallData_GetContracts(tt *testing.T) {
	c := &CallData{}
	c.GetContracts()
	c = nil
	c.GetContracts()
}

func TestCallData_GetControl(tt *testing.T) {
	c := &CallData{}
	c.GetControl()
	c = nil
	c.GetControl()
}

func TestCallData_GetDeviceMovements(tt *testing.T) {
	var zeroValue []DeviceMovementsHolder
	c := &CallData{DeviceMovements: &zeroValue}
	c.GetDeviceMovements()
	c = &CallData{}
	c.GetDeviceMovements()
	c = nil
	c.GetDeviceMovements()
}

func TestCallData_GetDevices(tt *testing.T) {
	c := &CallData{}
	c.GetDevices()
	c = nil
	c.GetDevices()
}

func TestCallData_GetExtTableValues(tt *testing.T) {
	c := &CallData{}
	c.GetExtTableValues()
	c = nil
	c.GetExtTableValues()
}

func TestCallData_GetFailureTypes(tt *testing.T) {
	c := &CallData{}
	c.GetFailureTypes()
	c = nil
	c.GetFailureTypes()
}

func TestCallData_GetImpacts(tt *testing.T) {
	c := &CallData{}
	c.GetImpacts()
	c = nil
	c.GetImpacts()
}

func TestCallData_GetLocations(tt *testing.T) {
	c := &CallData{}
	c.GetLocations()
	c = nil
	c.GetLocations()
}

func TestCallData_GetParentCall(tt *testing.T) {
	c := &CallData{}
	c.GetParentCall()
	c = nil
	c.GetParentCall()
}

func TestCallData_GetPriorities(tt *testing.T) {
	c := &CallData{}
	c.GetPriorities()
	c = nil
	c.GetPriorities()
}

func TestCallData_GetProblemTypes(tt *testing.T) {
	c := &CallData{}
	c.GetProblemTypes()
	c = nil
	c.GetProblemTypes()
}

func TestCallData_GetQueues1(tt *testing.T) {
	c := &CallData{}
	c.GetQueues1()
	c = nil
	c.GetQueues1()
}

func TestCallData_GetQueues2(tt *testing.T) {
	c := &CallData{}
	c.GetQueues2()
	c = nil
	c.GetQueues2()
}

func TestCallData_GetQueues3(tt *testing.T) {
	c := &CallData{}
	c.GetQueues3()
	c = nil
	c.GetQueues3()
}

func TestCallData_GetRequestTypes(tt *testing.T) {
	c := &CallData{}
	c.GetRequestTypes()
	c = nil
	c.GetRequestTypes()
}

func TestCallData_GetSeverities(tt *testing.T) {
	c := &CallData{}
	c.GetSeverities()
	c = nil
	c.GetSeverities()
}

func TestCallData_GetUrgency(tt *testing.T) {
	c := &CallData{}
	c.GetUrgency()
	c = nil
	c.GetUrgency()
}

func TestCallExtensionsHolder_GetField1(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field1: &zeroValue}
	c.GetField1()
	c = &CallExtensionsHolder{}
	c.GetField1()
	c = nil
	c.GetField1()
}

func TestCallExtensionsHolder_GetField10(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field10: &zeroValue}
	c.GetField10()
	c = &CallExtensionsHolder{}
	c.GetField10()
	c = nil
	c.GetField10()
}

func TestCallExtensionsHolder_GetField100(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field100: &zeroValue}
	c.GetField100()
	c = &CallExtensionsHolder{}
	c.GetField100()
	c = nil
	c.GetField100()
}

func TestCallExtensionsHolder_GetField101(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field101: &zeroValue}
	c.GetField101()
	c = &CallExtensionsHolder{}
	c.GetField101()
	c = nil
	c.GetField101()
}

func TestCallExtensionsHolder_GetField102(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field102: &zeroValue}
	c.GetField102()
	c = &CallExtensionsHolder{}
	c.GetField102()
	c = nil
	c.GetField102()
}

func TestCallExtensionsHolder_GetField103(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field103: &zeroValue}
	c.GetField103()
	c = &CallExtensionsHolder{}
	c.GetField103()
	c = nil
	c.GetField103()
}

func TestCallExtensionsHolder_GetField104(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field104: &zeroValue}
	c.GetField104()
	c = &CallExtensionsHolder{}
	c.GetField104()
	c = nil
	c.GetField104()
}

func TestCallExtensionsHolder_GetField105(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field105: &zeroValue}
	c.GetField105()
	c = &CallExtensionsHolder{}
	c.GetField105()
	c = nil
	c.GetField105()
}

func TestCallExtensionsHolder_GetField106(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field106: &zeroValue}
	c.GetField106()
	c = &CallExtensionsHolder{}
	c.GetField106()
	c = nil
	c.GetField106()
}

func TestCallExtensionsHolder_GetField107(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field107: &zeroValue}
	c.GetField107()
	c = &CallExtensionsHolder{}
	c.GetField107()
	c = nil
	c.GetField107()
}

func TestCallExtensionsHolder_GetField108(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field108: &zeroValue}
	c.GetField108()
	c = &CallExtensionsHolder{}
	c.GetField108()
	c = nil
	c.GetField108()
}

func TestCallExtensionsHolder_GetField109(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field109: &zeroValue}
	c.GetField109()
	c = &CallExtensionsHolder{}
	c.GetField109()
	c = nil
	c.GetField109()
}

func TestCallExtensionsHolder_GetField11(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field11: &zeroValue}
	c.GetField11()
	c = &CallExtensionsHolder{}
	c.GetField11()
	c = nil
	c.GetField11()
}

func TestCallExtensionsHolder_GetField110(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field110: &zeroValue}
	c.GetField110()
	c = &CallExtensionsHolder{}
	c.GetField110()
	c = nil
	c.GetField110()
}

func TestCallExtensionsHolder_GetField111(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field111: &zeroValue}
	c.GetField111()
	c = &CallExtensionsHolder{}
	c.GetField111()
	c = nil
	c.GetField111()
}

func TestCallExtensionsHolder_GetField112(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field112: &zeroValue}
	c.GetField112()
	c = &CallExtensionsHolder{}
	c.GetField112()
	c = nil
	c.GetField112()
}

func TestCallExtensionsHolder_GetField113(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field113: &zeroValue}
	c.GetField113()
	c = &CallExtensionsHolder{}
	c.GetField113()
	c = nil
	c.GetField113()
}

func TestCallExtensionsHolder_GetField114(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field114: &zeroValue}
	c.GetField114()
	c = &CallExtensionsHolder{}
	c.GetField114()
	c = nil
	c.GetField114()
}

func TestCallExtensionsHolder_GetField115(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field115: &zeroValue}
	c.GetField115()
	c = &CallExtensionsHolder{}
	c.GetField115()
	c = nil
	c.GetField115()
}

func TestCallExtensionsHolder_GetField116(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field116: &zeroValue}
	c.GetField116()
	c = &CallExtensionsHolder{}
	c.GetField116()
	c = nil
	c.GetField116()
}

func TestCallExtensionsHolder_GetField117(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field117: &zeroValue}
	c.GetField117()
	c = &CallExtensionsHolder{}
	c.GetField117()
	c = nil
	c.GetField117()
}

func TestCallExtensionsHolder_GetField118(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field118: &zeroValue}
	c.GetField118()
	c = &CallExtensionsHolder{}
	c.GetField118()
	c = nil
	c.GetField118()
}

func TestCallExtensionsHolder_GetField119(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field119: &zeroValue}
	c.GetField119()
	c = &CallExtensionsHolder{}
	c.GetField119()
	c = nil
	c.GetField119()
}

func TestCallExtensionsHolder_GetField12(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field12: &zeroValue}
	c.GetField12()
	c = &CallExtensionsHolder{}
	c.GetField12()
	c = nil
	c.GetField12()
}

func TestCallExtensionsHolder_GetField120(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field120: &zeroValue}
	c.GetField120()
	c = &CallExtensionsHolder{}
	c.GetField120()
	c = nil
	c.GetField120()
}

func TestCallExtensionsHolder_GetField121(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field121: &zeroValue}
	c.GetField121()
	c = &CallExtensionsHolder{}
	c.GetField121()
	c = nil
	c.GetField121()
}

func TestCallExtensionsHolder_GetField122(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field122: &zeroValue}
	c.GetField122()
	c = &CallExtensionsHolder{}
	c.GetField122()
	c = nil
	c.GetField122()
}

func TestCallExtensionsHolder_GetField123(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field123: &zeroValue}
	c.GetField123()
	c = &CallExtensionsHolder{}
	c.GetField123()
	c = nil
	c.GetField123()
}

func TestCallExtensionsHolder_GetField124(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field124: &zeroValue}
	c.GetField124()
	c = &CallExtensionsHolder{}
	c.GetField124()
	c = nil
	c.GetField124()
}

func TestCallExtensionsHolder_GetField125(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field125: &zeroValue}
	c.GetField125()
	c = &CallExtensionsHolder{}
	c.GetField125()
	c = nil
	c.GetField125()
}

func TestCallExtensionsHolder_GetField126(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field126: &zeroValue}
	c.GetField126()
	c = &CallExtensionsHolder{}
	c.GetField126()
	c = nil
	c.GetField126()
}

func TestCallExtensionsHolder_GetField127(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field127: &zeroValue}
	c.GetField127()
	c = &CallExtensionsHolder{}
	c.GetField127()
	c = nil
	c.GetField127()
}

func TestCallExtensionsHolder_GetField128(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field128: &zeroValue}
	c.GetField128()
	c = &CallExtensionsHolder{}
	c.GetField128()
	c = nil
	c.GetField128()
}

func TestCallExtensionsHolder_GetField13(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field13: &zeroValue}
	c.GetField13()
	c = &CallExtensionsHolder{}
	c.GetField13()
	c = nil
	c.GetField13()
}

func TestCallExtensionsHolder_GetField14(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field14: &zeroValue}
	c.GetField14()
	c = &CallExtensionsHolder{}
	c.GetField14()
	c = nil
	c.GetField14()
}

func TestCallExtensionsHolder_GetField15(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field15: &zeroValue}
	c.GetField15()
	c = &CallExtensionsHolder{}
	c.GetField15()
	c = nil
	c.GetField15()
}

func TestCallExtensionsHolder_GetField16(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field16: &zeroValue}
	c.GetField16()
	c = &CallExtensionsHolder{}
	c.GetField16()
	c = nil
	c.GetField16()
}

func TestCallExtensionsHolder_GetField17(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field17: &zeroValue}
	c.GetField17()
	c = &CallExtensionsHolder{}
	c.GetField17()
	c = nil
	c.GetField17()
}

func TestCallExtensionsHolder_GetField18(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field18: &zeroValue}
	c.GetField18()
	c = &CallExtensionsHolder{}
	c.GetField18()
	c = nil
	c.GetField18()
}

func TestCallExtensionsHolder_GetField19(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field19: &zeroValue}
	c.GetField19()
	c = &CallExtensionsHolder{}
	c.GetField19()
	c = nil
	c.GetField19()
}

func TestCallExtensionsHolder_GetField2(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field2: &zeroValue}
	c.GetField2()
	c = &CallExtensionsHolder{}
	c.GetField2()
	c = nil
	c.GetField2()
}

func TestCallExtensionsHolder_GetField20(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field20: &zeroValue}
	c.GetField20()
	c = &CallExtensionsHolder{}
	c.GetField20()
	c = nil
	c.GetField20()
}

func TestCallExtensionsHolder_GetField21(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field21: &zeroValue}
	c.GetField21()
	c = &CallExtensionsHolder{}
	c.GetField21()
	c = nil
	c.GetField21()
}

func TestCallExtensionsHolder_GetField22(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field22: &zeroValue}
	c.GetField22()
	c = &CallExtensionsHolder{}
	c.GetField22()
	c = nil
	c.GetField22()
}

func TestCallExtensionsHolder_GetField23(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field23: &zeroValue}
	c.GetField23()
	c = &CallExtensionsHolder{}
	c.GetField23()
	c = nil
	c.GetField23()
}

func TestCallExtensionsHolder_GetField24(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field24: &zeroValue}
	c.GetField24()
	c = &CallExtensionsHolder{}
	c.GetField24()
	c = nil
	c.GetField24()
}

func TestCallExtensionsHolder_GetField25(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field25: &zeroValue}
	c.GetField25()
	c = &CallExtensionsHolder{}
	c.GetField25()
	c = nil
	c.GetField25()
}

func TestCallExtensionsHolder_GetField26(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field26: &zeroValue}
	c.GetField26()
	c = &CallExtensionsHolder{}
	c.GetField26()
	c = nil
	c.GetField26()
}

func TestCallExtensionsHolder_GetField27(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field27: &zeroValue}
	c.GetField27()
	c = &CallExtensionsHolder{}
	c.GetField27()
	c = nil
	c.GetField27()
}

func TestCallExtensionsHolder_GetField28(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field28: &zeroValue}
	c.GetField28()
	c = &CallExtensionsHolder{}
	c.GetField28()
	c = nil
	c.GetField28()
}

func TestCallExtensionsHolder_GetField29(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field29: &zeroValue}
	c.GetField29()
	c = &CallExtensionsHolder{}
	c.GetField29()
	c = nil
	c.GetField29()
}

func TestCallExtensionsHolder_GetField3(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field3: &zeroValue}
	c.GetField3()
	c = &CallExtensionsHolder{}
	c.GetField3()
	c = nil
	c.GetField3()
}

func TestCallExtensionsHolder_GetField30(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field30: &zeroValue}
	c.GetField30()
	c = &CallExtensionsHolder{}
	c.GetField30()
	c = nil
	c.GetField30()
}

func TestCallExtensionsHolder_GetField31(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field31: &zeroValue}
	c.GetField31()
	c = &CallExtensionsHolder{}
	c.GetField31()
	c = nil
	c.GetField31()
}

func TestCallExtensionsHolder_GetField32(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field32: &zeroValue}
	c.GetField32()
	c = &CallExtensionsHolder{}
	c.GetField32()
	c = nil
	c.GetField32()
}

func TestCallExtensionsHolder_GetField33(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field33: &zeroValue}
	c.GetField33()
	c = &CallExtensionsHolder{}
	c.GetField33()
	c = nil
	c.GetField33()
}

func TestCallExtensionsHolder_GetField34(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field34: &zeroValue}
	c.GetField34()
	c = &CallExtensionsHolder{}
	c.GetField34()
	c = nil
	c.GetField34()
}

func TestCallExtensionsHolder_GetField35(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field35: &zeroValue}
	c.GetField35()
	c = &CallExtensionsHolder{}
	c.GetField35()
	c = nil
	c.GetField35()
}

func TestCallExtensionsHolder_GetField36(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field36: &zeroValue}
	c.GetField36()
	c = &CallExtensionsHolder{}
	c.GetField36()
	c = nil
	c.GetField36()
}

func TestCallExtensionsHolder_GetField37(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field37: &zeroValue}
	c.GetField37()
	c = &CallExtensionsHolder{}
	c.GetField37()
	c = nil
	c.GetField37()
}

func TestCallExtensionsHolder_GetField38(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field38: &zeroValue}
	c.GetField38()
	c = &CallExtensionsHolder{}
	c.GetField38()
	c = nil
	c.GetField38()
}

func TestCallExtensionsHolder_GetField39(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field39: &zeroValue}
	c.GetField39()
	c = &CallExtensionsHolder{}
	c.GetField39()
	c = nil
	c.GetField39()
}

func TestCallExtensionsHolder_GetField4(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field4: &zeroValue}
	c.GetField4()
	c = &CallExtensionsHolder{}
	c.GetField4()
	c = nil
	c.GetField4()
}

func TestCallExtensionsHolder_GetField40(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field40: &zeroValue}
	c.GetField40()
	c = &CallExtensionsHolder{}
	c.GetField40()
	c = nil
	c.GetField40()
}

func TestCallExtensionsHolder_GetField41(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field41: &zeroValue}
	c.GetField41()
	c = &CallExtensionsHolder{}
	c.GetField41()
	c = nil
	c.GetField41()
}

func TestCallExtensionsHolder_GetField42(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field42: &zeroValue}
	c.GetField42()
	c = &CallExtensionsHolder{}
	c.GetField42()
	c = nil
	c.GetField42()
}

func TestCallExtensionsHolder_GetField43(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field43: &zeroValue}
	c.GetField43()
	c = &CallExtensionsHolder{}
	c.GetField43()
	c = nil
	c.GetField43()
}

func TestCallExtensionsHolder_GetField44(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field44: &zeroValue}
	c.GetField44()
	c = &CallExtensionsHolder{}
	c.GetField44()
	c = nil
	c.GetField44()
}

func TestCallExtensionsHolder_GetField45(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field45: &zeroValue}
	c.GetField45()
	c = &CallExtensionsHolder{}
	c.GetField45()
	c = nil
	c.GetField45()
}

func TestCallExtensionsHolder_GetField46(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field46: &zeroValue}
	c.GetField46()
	c = &CallExtensionsHolder{}
	c.GetField46()
	c = nil
	c.GetField46()
}

func TestCallExtensionsHolder_GetField47(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field47: &zeroValue}
	c.GetField47()
	c = &CallExtensionsHolder{}
	c.GetField47()
	c = nil
	c.GetField47()
}

func TestCallExtensionsHolder_GetField48(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field48: &zeroValue}
	c.GetField48()
	c = &CallExtensionsHolder{}
	c.GetField48()
	c = nil
	c.GetField48()
}

func TestCallExtensionsHolder_GetField49(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field49: &zeroValue}
	c.GetField49()
	c = &CallExtensionsHolder{}
	c.GetField49()
	c = nil
	c.GetField49()
}

func TestCallExtensionsHolder_GetField5(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field5: &zeroValue}
	c.GetField5()
	c = &CallExtensionsHolder{}
	c.GetField5()
	c = nil
	c.GetField5()
}

func TestCallExtensionsHolder_GetField50(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field50: &zeroValue}
	c.GetField50()
	c = &CallExtensionsHolder{}
	c.GetField50()
	c = nil
	c.GetField50()
}

func TestCallExtensionsHolder_GetField51(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field51: &zeroValue}
	c.GetField51()
	c = &CallExtensionsHolder{}
	c.GetField51()
	c = nil
	c.GetField51()
}

func TestCallExtensionsHolder_GetField52(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field52: &zeroValue}
	c.GetField52()
	c = &CallExtensionsHolder{}
	c.GetField52()
	c = nil
	c.GetField52()
}

func TestCallExtensionsHolder_GetField53(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field53: &zeroValue}
	c.GetField53()
	c = &CallExtensionsHolder{}
	c.GetField53()
	c = nil
	c.GetField53()
}

func TestCallExtensionsHolder_GetField54(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field54: &zeroValue}
	c.GetField54()
	c = &CallExtensionsHolder{}
	c.GetField54()
	c = nil
	c.GetField54()
}

func TestCallExtensionsHolder_GetField55(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field55: &zeroValue}
	c.GetField55()
	c = &CallExtensionsHolder{}
	c.GetField55()
	c = nil
	c.GetField55()
}

func TestCallExtensionsHolder_GetField56(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field56: &zeroValue}
	c.GetField56()
	c = &CallExtensionsHolder{}
	c.GetField56()
	c = nil
	c.GetField56()
}

func TestCallExtensionsHolder_GetField57(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field57: &zeroValue}
	c.GetField57()
	c = &CallExtensionsHolder{}
	c.GetField57()
	c = nil
	c.GetField57()
}

func TestCallExtensionsHolder_GetField58(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field58: &zeroValue}
	c.GetField58()
	c = &CallExtensionsHolder{}
	c.GetField58()
	c = nil
	c.GetField58()
}

func TestCallExtensionsHolder_GetField59(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field59: &zeroValue}
	c.GetField59()
	c = &CallExtensionsHolder{}
	c.GetField59()
	c = nil
	c.GetField59()
}

func TestCallExtensionsHolder_GetField6(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field6: &zeroValue}
	c.GetField6()
	c = &CallExtensionsHolder{}
	c.GetField6()
	c = nil
	c.GetField6()
}

func TestCallExtensionsHolder_GetField60(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field60: &zeroValue}
	c.GetField60()
	c = &CallExtensionsHolder{}
	c.GetField60()
	c = nil
	c.GetField60()
}

func TestCallExtensionsHolder_GetField61(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field61: &zeroValue}
	c.GetField61()
	c = &CallExtensionsHolder{}
	c.GetField61()
	c = nil
	c.GetField61()
}

func TestCallExtensionsHolder_GetField62(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field62: &zeroValue}
	c.GetField62()
	c = &CallExtensionsHolder{}
	c.GetField62()
	c = nil
	c.GetField62()
}

func TestCallExtensionsHolder_GetField63(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field63: &zeroValue}
	c.GetField63()
	c = &CallExtensionsHolder{}
	c.GetField63()
	c = nil
	c.GetField63()
}

func TestCallExtensionsHolder_GetField64(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field64: &zeroValue}
	c.GetField64()
	c = &CallExtensionsHolder{}
	c.GetField64()
	c = nil
	c.GetField64()
}

func TestCallExtensionsHolder_GetField65(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field65: &zeroValue}
	c.GetField65()
	c = &CallExtensionsHolder{}
	c.GetField65()
	c = nil
	c.GetField65()
}

func TestCallExtensionsHolder_GetField66(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field66: &zeroValue}
	c.GetField66()
	c = &CallExtensionsHolder{}
	c.GetField66()
	c = nil
	c.GetField66()
}

func TestCallExtensionsHolder_GetField67(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field67: &zeroValue}
	c.GetField67()
	c = &CallExtensionsHolder{}
	c.GetField67()
	c = nil
	c.GetField67()
}

func TestCallExtensionsHolder_GetField68(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field68: &zeroValue}
	c.GetField68()
	c = &CallExtensionsHolder{}
	c.GetField68()
	c = nil
	c.GetField68()
}

func TestCallExtensionsHolder_GetField69(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field69: &zeroValue}
	c.GetField69()
	c = &CallExtensionsHolder{}
	c.GetField69()
	c = nil
	c.GetField69()
}

func TestCallExtensionsHolder_GetField7(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field7: &zeroValue}
	c.GetField7()
	c = &CallExtensionsHolder{}
	c.GetField7()
	c = nil
	c.GetField7()
}

func TestCallExtensionsHolder_GetField70(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field70: &zeroValue}
	c.GetField70()
	c = &CallExtensionsHolder{}
	c.GetField70()
	c = nil
	c.GetField70()
}

func TestCallExtensionsHolder_GetField71(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field71: &zeroValue}
	c.GetField71()
	c = &CallExtensionsHolder{}
	c.GetField71()
	c = nil
	c.GetField71()
}

func TestCallExtensionsHolder_GetField72(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field72: &zeroValue}
	c.GetField72()
	c = &CallExtensionsHolder{}
	c.GetField72()
	c = nil
	c.GetField72()
}

func TestCallExtensionsHolder_GetField73(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field73: &zeroValue}
	c.GetField73()
	c = &CallExtensionsHolder{}
	c.GetField73()
	c = nil
	c.GetField73()
}

func TestCallExtensionsHolder_GetField74(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field74: &zeroValue}
	c.GetField74()
	c = &CallExtensionsHolder{}
	c.GetField74()
	c = nil
	c.GetField74()
}

func TestCallExtensionsHolder_GetField75(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field75: &zeroValue}
	c.GetField75()
	c = &CallExtensionsHolder{}
	c.GetField75()
	c = nil
	c.GetField75()
}

func TestCallExtensionsHolder_GetField76(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field76: &zeroValue}
	c.GetField76()
	c = &CallExtensionsHolder{}
	c.GetField76()
	c = nil
	c.GetField76()
}

func TestCallExtensionsHolder_GetField77(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field77: &zeroValue}
	c.GetField77()
	c = &CallExtensionsHolder{}
	c.GetField77()
	c = nil
	c.GetField77()
}

func TestCallExtensionsHolder_GetField78(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field78: &zeroValue}
	c.GetField78()
	c = &CallExtensionsHolder{}
	c.GetField78()
	c = nil
	c.GetField78()
}

func TestCallExtensionsHolder_GetField79(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field79: &zeroValue}
	c.GetField79()
	c = &CallExtensionsHolder{}
	c.GetField79()
	c = nil
	c.GetField79()
}

func TestCallExtensionsHolder_GetField8(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field8: &zeroValue}
	c.GetField8()
	c = &CallExtensionsHolder{}
	c.GetField8()
	c = nil
	c.GetField8()
}

func TestCallExtensionsHolder_GetField80(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field80: &zeroValue}
	c.GetField80()
	c = &CallExtensionsHolder{}
	c.GetField80()
	c = nil
	c.GetField80()
}

func TestCallExtensionsHolder_GetField81(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field81: &zeroValue}
	c.GetField81()
	c = &CallExtensionsHolder{}
	c.GetField81()
	c = nil
	c.GetField81()
}

func TestCallExtensionsHolder_GetField82(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field82: &zeroValue}
	c.GetField82()
	c = &CallExtensionsHolder{}
	c.GetField82()
	c = nil
	c.GetField82()
}

func TestCallExtensionsHolder_GetField83(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field83: &zeroValue}
	c.GetField83()
	c = &CallExtensionsHolder{}
	c.GetField83()
	c = nil
	c.GetField83()
}

func TestCallExtensionsHolder_GetField84(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field84: &zeroValue}
	c.GetField84()
	c = &CallExtensionsHolder{}
	c.GetField84()
	c = nil
	c.GetField84()
}

func TestCallExtensionsHolder_GetField85(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field85: &zeroValue}
	c.GetField85()
	c = &CallExtensionsHolder{}
	c.GetField85()
	c = nil
	c.GetField85()
}

func TestCallExtensionsHolder_GetField86(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field86: &zeroValue}
	c.GetField86()
	c = &CallExtensionsHolder{}
	c.GetField86()
	c = nil
	c.GetField86()
}

func TestCallExtensionsHolder_GetField87(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field87: &zeroValue}
	c.GetField87()
	c = &CallExtensionsHolder{}
	c.GetField87()
	c = nil
	c.GetField87()
}

func TestCallExtensionsHolder_GetField88(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field88: &zeroValue}
	c.GetField88()
	c = &CallExtensionsHolder{}
	c.GetField88()
	c = nil
	c.GetField88()
}

func TestCallExtensionsHolder_GetField89(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field89: &zeroValue}
	c.GetField89()
	c = &CallExtensionsHolder{}
	c.GetField89()
	c = nil
	c.GetField89()
}

func TestCallExtensionsHolder_GetField9(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field9: &zeroValue}
	c.GetField9()
	c = &CallExtensionsHolder{}
	c.GetField9()
	c = nil
	c.GetField9()
}

func TestCallExtensionsHolder_GetField90(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field90: &zeroValue}
	c.GetField90()
	c = &CallExtensionsHolder{}
	c.GetField90()
	c = nil
	c.GetField90()
}

func TestCallExtensionsHolder_GetField91(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field91: &zeroValue}
	c.GetField91()
	c = &CallExtensionsHolder{}
	c.GetField91()
	c = nil
	c.GetField91()
}

func TestCallExtensionsHolder_GetField92(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field92: &zeroValue}
	c.GetField92()
	c = &CallExtensionsHolder{}
	c.GetField92()
	c = nil
	c.GetField92()
}

func TestCallExtensionsHolder_GetField93(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field93: &zeroValue}
	c.GetField93()
	c = &CallExtensionsHolder{}
	c.GetField93()
	c = nil
	c.GetField93()
}

func TestCallExtensionsHolder_GetField94(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field94: &zeroValue}
	c.GetField94()
	c = &CallExtensionsHolder{}
	c.GetField94()
	c = nil
	c.GetField94()
}

func TestCallExtensionsHolder_GetField95(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field95: &zeroValue}
	c.GetField95()
	c = &CallExtensionsHolder{}
	c.GetField95()
	c = nil
	c.GetField95()
}

func TestCallExtensionsHolder_GetField96(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field96: &zeroValue}
	c.GetField96()
	c = &CallExtensionsHolder{}
	c.GetField96()
	c = nil
	c.GetField96()
}

func TestCallExtensionsHolder_GetField97(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field97: &zeroValue}
	c.GetField97()
	c = &CallExtensionsHolder{}
	c.GetField97()
	c = nil
	c.GetField97()
}

func TestCallExtensionsHolder_GetField98(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field98: &zeroValue}
	c.GetField98()
	c = &CallExtensionsHolder{}
	c.GetField98()
	c = nil
	c.GetField98()
}

func TestCallExtensionsHolder_GetField99(tt *testing.T) {
	var zeroValue string
	c := &CallExtensionsHolder{Field99: &zeroValue}
	c.GetField99()
	c = &CallExtensionsHolder{}
	c.GetField99()
	c = nil
	c.GetField99()
}

func TestCallNotesHolder_GetIsPrivate(tt *testing.T) {
	var zeroValue string
	c := &CallNotesHolder{IsPrivate: &zeroValue}
	c.GetIsPrivate()
	c = &CallNotesHolder{}
	c.GetIsPrivate()
	c = nil
	c.GetIsPrivate()
}

func TestCallNotesHolder_GetType(tt *testing.T) {
	var zeroValue string
	c := &CallNotesHolder{Type: &zeroValue}
	c.GetType()
	c = &CallNotesHolder{}
	c.GetType()
	c = nil
	c.GetType()
}

func TestCallNotesHolder_GetValue(tt *testing.T) {
	var zeroValue string
	c := &CallNotesHolder{Value: &zeroValue}
	c.GetValue()
	c = &CallNotesHolder{}
	c.GetValue()
	c = nil
	c.GetValue()
}

func TestCallSystemCodesHolder_GetName(tt *testing.T) {
	var zeroValue string
	c := &CallSystemCodesHolder{Name: &zeroValue}
	c.GetName()
	c = &CallSystemCodesHolder{}
	c.GetName()
	c = nil
	c.GetName()
}

func TestCallSystemCodesHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	c := &CallSystemCodesHolder{ShortName: &zeroValue}
	c.GetShortName()
	c = &CallSystemCodesHolder{}
	c.GetShortName()
	c = nil
	c.GetShortName()
}

func TestChargingTypesHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	c := &ChargingTypesHolder{ShortName: &zeroValue}
	c.GetShortName()
	c = &ChargingTypesHolder{}
	c.GetShortName()
	c = nil
	c.GetShortName()
}

func TestComponentsHolder_GetComponent(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{Component: &zeroValue}
	c.GetComponent()
	c = &ComponentsHolder{}
	c.GetComponent()
	c = nil
	c.GetComponent()
}

func TestComponentsHolder_GetDescription(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{Description: &zeroValue}
	c.GetDescription()
	c = &ComponentsHolder{}
	c.GetDescription()
	c = nil
	c.GetDescription()
}

func TestComponentsHolder_GetHostname(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{Hostname: &zeroValue}
	c.GetHostname()
	c = &ComponentsHolder{}
	c.GetHostname()
	c = nil
	c.GetHostname()
}

func TestComponentsHolder_GetInvNr(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{InvNr: &zeroValue}
	c.GetInvNr()
	c = &ComponentsHolder{}
	c.GetInvNr()
	c = nil
	c.GetInvNr()
}

func TestComponentsHolder_GetIPAddress(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{IPAddress: &zeroValue}
	c.GetIPAddress()
	c = &ComponentsHolder{}
	c.GetIPAddress()
	c = nil
	c.GetIPAddress()
}

func TestComponentsHolder_GetLocation(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{Location: &zeroValue}
	c.GetLocation()
	c = &ComponentsHolder{}
	c.GetLocation()
	c = nil
	c.GetLocation()
}

func TestComponentsHolder_GetLocationCategory(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationCategory: &zeroValue}
	c.GetLocationCategory()
	c = &ComponentsHolder{}
	c.GetLocationCategory()
	c = nil
	c.GetLocationCategory()
}

func TestComponentsHolder_GetLocationCity(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationCity: &zeroValue}
	c.GetLocationCity()
	c = &ComponentsHolder{}
	c.GetLocationCity()
	c = nil
	c.GetLocationCity()
}

func TestComponentsHolder_GetLocationCountry(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationCountry: &zeroValue}
	c.GetLocationCountry()
	c = &ComponentsHolder{}
	c.GetLocationCountry()
	c = nil
	c.GetLocationCountry()
}

func TestComponentsHolder_GetLocationDescription(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationDescription: &zeroValue}
	c.GetLocationDescription()
	c = &ComponentsHolder{}
	c.GetLocationDescription()
	c = nil
	c.GetLocationDescription()
}

func TestComponentsHolder_GetLocationLevel(tt *testing.T) {
	var zeroValue float32
	c := &ComponentsHolder{LocationLevel: &zeroValue}
	c.GetLocationLevel()
	c = &ComponentsHolder{}
	c.GetLocationLevel()
	c = nil
	c.GetLocationLevel()
}

func TestComponentsHolder_GetLocationName(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationName: &zeroValue}
	c.GetLocationName()
	c = &ComponentsHolder{}
	c.GetLocationName()
	c = nil
	c.GetLocationName()
}

func TestComponentsHolder_GetLocationProvince(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationProvince: &zeroValue}
	c.GetLocationProvince()
	c = &ComponentsHolder{}
	c.GetLocationProvince()
	c = nil
	c.GetLocationProvince()
}

func TestComponentsHolder_GetLocationRegion(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationRegion: &zeroValue}
	c.GetLocationRegion()
	c = &ComponentsHolder{}
	c.GetLocationRegion()
	c = nil
	c.GetLocationRegion()
}

func TestComponentsHolder_GetLocationStreet(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationStreet: &zeroValue}
	c.GetLocationStreet()
	c = &ComponentsHolder{}
	c.GetLocationStreet()
	c = nil
	c.GetLocationStreet()
}

func TestComponentsHolder_GetLocationTel(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationTel: &zeroValue}
	c.GetLocationTel()
	c = &ComponentsHolder{}
	c.GetLocationTel()
	c = nil
	c.GetLocationTel()
}

func TestComponentsHolder_GetLocationZip(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{LocationZip: &zeroValue}
	c.GetLocationZip()
	c = &ComponentsHolder{}
	c.GetLocationZip()
	c = nil
	c.GetLocationZip()
}

func TestComponentsHolder_GetMACAddress(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{MACAddress: &zeroValue}
	c.GetMACAddress()
	c = &ComponentsHolder{}
	c.GetMACAddress()
	c = nil
	c.GetMACAddress()
}

func TestComponentsHolder_GetManufacturer(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{Manufacturer: &zeroValue}
	c.GetManufacturer()
	c = &ComponentsHolder{}
	c.GetManufacturer()
	c = nil
	c.GetManufacturer()
}

func TestComponentsHolder_GetModel(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{Model: &zeroValue}
	c.GetModel()
	c = &ComponentsHolder{}
	c.GetModel()
	c = nil
	c.GetModel()
}

func TestComponentsHolder_GetName(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{Name: &zeroValue}
	c.GetName()
	c = &ComponentsHolder{}
	c.GetName()
	c = nil
	c.GetName()
}

func TestComponentsHolder_GetOpSys(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{OpSys: &zeroValue}
	c.GetOpSys()
	c = &ComponentsHolder{}
	c.GetOpSys()
	c = nil
	c.GetOpSys()
}

func TestComponentsHolder_GetRoom(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{Room: &zeroValue}
	c.GetRoom()
	c = &ComponentsHolder{}
	c.GetRoom()
	c = nil
	c.GetRoom()
}

func TestComponentsHolder_GetSerNr(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{SerNr: &zeroValue}
	c.GetSerNr()
	c = &ComponentsHolder{}
	c.GetSerNr()
	c = nil
	c.GetSerNr()
}

func TestComponentsHolder_GetSerNrProv(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{SerNrProv: &zeroValue}
	c.GetSerNrProv()
	c = &ComponentsHolder{}
	c.GetSerNrProv()
	c = nil
	c.GetSerNrProv()
}

func TestComponentsHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{ShortName: &zeroValue}
	c.GetShortName()
	c = &ComponentsHolder{}
	c.GetShortName()
	c = nil
	c.GetShortName()
}

func TestComponentsHolder_GetType(tt *testing.T) {
	var zeroValue string
	c := &ComponentsHolder{Type: &zeroValue}
	c.GetType()
	c = &ComponentsHolder{}
	c.GetType()
	c = nil
	c.GetType()
}

func TestControlFlagsHolder_GetDeactivateOutboundTriggers(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{DeactivateOutboundTriggers: &zeroValue}
	c.GetDeactivateOutboundTriggers()
	c = &ControlFlagsHolder{}
	c.GetDeactivateOutboundTriggers()
	c = nil
	c.GetDeactivateOutboundTriggers()
}

func TestControlFlagsHolder_GetForwardAfterClose(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{ForwardAfterClose: &zeroValue}
	c.GetForwardAfterClose()
	c = &ControlFlagsHolder{}
	c.GetForwardAfterClose()
	c = nil
	c.GetForwardAfterClose()
}

func TestControlFlagsHolder_GetMakePreSelection(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{MakePreSelection: &zeroValue}
	c.GetMakePreSelection()
	c = &ControlFlagsHolder{}
	c.GetMakePreSelection()
	c = nil
	c.GetMakePreSelection()
}

func TestControlFlagsHolder_GetMergeDefaultsOnContractOrContractElementChange(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{MergeDefaultsOnContractOrContractElementChange: &zeroValue}
	c.GetMergeDefaultsOnContractOrContractElementChange()
	c = &ControlFlagsHolder{}
	c.GetMergeDefaultsOnContractOrContractElementChange()
	c = nil
	c.GetMergeDefaultsOnContractOrContractElementChange()
}

func TestControlFlagsHolder_GetMergeLocationFromCaller(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{MergeLocationFromCaller: &zeroValue}
	c.GetMergeLocationFromCaller()
	c = &ControlFlagsHolder{}
	c.GetMergeLocationFromCaller()
	c = nil
	c.GetMergeLocationFromCaller()
}

func TestControlFlagsHolder_GetSetCurrentCallState(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{SetCurrentCallState: &zeroValue}
	c.GetSetCurrentCallState()
	c = &ControlFlagsHolder{}
	c.GetSetCurrentCallState()
	c = nil
	c.GetSetCurrentCallState()
}

func TestControlFlagsHolder_GetUpdateAfterCloseAllowed(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{UpdateAfterCloseAllowed: &zeroValue}
	c.GetUpdateAfterCloseAllowed()
	c = &ControlFlagsHolder{}
	c.GetUpdateAfterCloseAllowed()
	c = nil
	c.GetUpdateAfterCloseAllowed()
}

func TestControlFlagsHolder_GetUseCodeDefaults(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{UseCodeDefaults: &zeroValue}
	c.GetUseCodeDefaults()
	c = &ControlFlagsHolder{}
	c.GetUseCodeDefaults()
	c = nil
	c.GetUseCodeDefaults()
}

func TestControlFlagsHolder_GetUseIndependentDeviceRef(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{UseIndependentDeviceRef: &zeroValue}
	c.GetUseIndependentDeviceRef()
	c = &ControlFlagsHolder{}
	c.GetUseIndependentDeviceRef()
	c = nil
	c.GetUseIndependentDeviceRef()
}

func TestControlFlagsHolder_GetUsePartnerSideSuccessors(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{UsePartnerSideSuccessors: &zeroValue}
	c.GetUsePartnerSideSuccessors()
	c = &ControlFlagsHolder{}
	c.GetUsePartnerSideSuccessors()
	c = nil
	c.GetUsePartnerSideSuccessors()
}

func TestControlFlagsHolder_GetUseSuccessors(tt *testing.T) {
	var zeroValue string
	c := &ControlFlagsHolder{UseSuccessors: &zeroValue}
	c.GetUseSuccessors()
	c = &ControlFlagsHolder{}
	c.GetUseSuccessors()
	c = nil
	c.GetUseSuccessors()
}

func TestDeviceMovementsDeviceHolder_GetComponent(tt *testing.T) {
	var zeroValue string
	d := &DeviceMovementsDeviceHolder{Component: &zeroValue}
	d.GetComponent()
	d = &DeviceMovementsDeviceHolder{}
	d.GetComponent()
	d = nil
	d.GetComponent()
}

func TestDeviceMovementsDeviceHolder_GetInvNr(tt *testing.T) {
	var zeroValue string
	d := &DeviceMovementsDeviceHolder{InvNr: &zeroValue}
	d.GetInvNr()
	d = &DeviceMovementsDeviceHolder{}
	d.GetInvNr()
	d = nil
	d.GetInvNr()
}

func TestDeviceMovementsDeviceHolder_GetManufacturer(tt *testing.T) {
	var zeroValue string
	d := &DeviceMovementsDeviceHolder{Manufacturer: &zeroValue}
	d.GetManufacturer()
	d = &DeviceMovementsDeviceHolder{}
	d.GetManufacturer()
	d = nil
	d.GetManufacturer()
}

func TestDeviceMovementsDeviceHolder_GetModel(tt *testing.T) {
	var zeroValue string
	d := &DeviceMovementsDeviceHolder{Model: &zeroValue}
	d.GetModel()
	d = &DeviceMovementsDeviceHolder{}
	d.GetModel()
	d = nil
	d.GetModel()
}

func TestDeviceMovementsDeviceHolder_GetOwner(tt *testing.T) {
	var zeroValue string
	d := &DeviceMovementsDeviceHolder{Owner: &zeroValue}
	d.GetOwner()
	d = &DeviceMovementsDeviceHolder{}
	d.GetOwner()
	d = nil
	d.GetOwner()
}

func TestDeviceMovementsDeviceHolder_GetSerNr(tt *testing.T) {
	var zeroValue string
	d := &DeviceMovementsDeviceHolder{SerNr: &zeroValue}
	d.GetSerNr()
	d = &DeviceMovementsDeviceHolder{}
	d.GetSerNr()
	d = nil
	d.GetSerNr()
}

func TestDeviceMovementsDeviceHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	d := &DeviceMovementsDeviceHolder{ShortName: &zeroValue}
	d.GetShortName()
	d = &DeviceMovementsDeviceHolder{}
	d.GetShortName()
	d = nil
	d.GetShortName()
}

func TestDeviceMovementsDeviceHolder_GetType(tt *testing.T) {
	var zeroValue string
	d := &DeviceMovementsDeviceHolder{Type: &zeroValue}
	d.GetType()
	d = &DeviceMovementsDeviceHolder{}
	d.GetType()
	d = nil
	d.GetType()
}

func TestDeviceMovementsDeviceHolder_GetUNSPSC(tt *testing.T) {
	var zeroValue string
	d := &DeviceMovementsDeviceHolder{UNSPSC: &zeroValue}
	d.GetUNSPSC()
	d = &DeviceMovementsDeviceHolder{}
	d.GetUNSPSC()
	d = nil
	d.GetUNSPSC()
}

func TestDeviceMovementsHolder_GetDevice(tt *testing.T) {
	d := &DeviceMovementsHolder{}
	d.GetDevice()
	d = nil
	d.GetDevice()
}

func TestDeviceMovementsHolder_GetFromLocation(tt *testing.T) {
	d := &DeviceMovementsHolder{}
	d.GetFromLocation()
	d = nil
	d.GetFromLocation()
}

func TestDeviceMovementsHolder_GetToLocation(tt *testing.T) {
	d := &DeviceMovementsHolder{}
	d.GetToLocation()
	d = nil
	d.GetToLocation()
}

func TestDevicesHolder_GetComponent(tt *testing.T) {
	var zeroValue string
	d := &DevicesHolder{Component: &zeroValue}
	d.GetComponent()
	d = &DevicesHolder{}
	d.GetComponent()
	d = nil
	d.GetComponent()
}

func TestDevicesHolder_GetInvNr(tt *testing.T) {
	var zeroValue string
	d := &DevicesHolder{InvNr: &zeroValue}
	d.GetInvNr()
	d = &DevicesHolder{}
	d.GetInvNr()
	d = nil
	d.GetInvNr()
}

func TestDevicesHolder_GetManufacturer(tt *testing.T) {
	var zeroValue string
	d := &DevicesHolder{Manufacturer: &zeroValue}
	d.GetManufacturer()
	d = &DevicesHolder{}
	d.GetManufacturer()
	d = nil
	d.GetManufacturer()
}

func TestDevicesHolder_GetModel(tt *testing.T) {
	var zeroValue string
	d := &DevicesHolder{Model: &zeroValue}
	d.GetModel()
	d = &DevicesHolder{}
	d.GetModel()
	d = nil
	d.GetModel()
}

func TestDevicesHolder_GetSerNr(tt *testing.T) {
	var zeroValue string
	d := &DevicesHolder{SerNr: &zeroValue}
	d.GetSerNr()
	d = &DevicesHolder{}
	d.GetSerNr()
	d = nil
	d.GetSerNr()
}

func TestDevicesHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	d := &DevicesHolder{ShortName: &zeroValue}
	d.GetShortName()
	d = &DevicesHolder{}
	d.GetShortName()
	d = nil
	d.GetShortName()
}

func TestDevicesHolder_GetType(tt *testing.T) {
	var zeroValue string
	d := &DevicesHolder{Type: &zeroValue}
	d.GetType()
	d = &DevicesHolder{}
	d.GetType()
	d = nil
	d.GetType()
}

func TestDevicesHolder_GetUNSPSC(tt *testing.T) {
	var zeroValue string
	d := &DevicesHolder{UNSPSC: &zeroValue}
	d.GetUNSPSC()
	d = &DevicesHolder{}
	d.GetUNSPSC()
	d = nil
	d.GetUNSPSC()
}

func TestEntityTypesHolder_GetName(tt *testing.T) {
	var zeroValue string
	e := &EntityTypesHolder{Name: &zeroValue}
	e.GetName()
	e = &EntityTypesHolder{}
	e.GetName()
	e = nil
	e.GetName()
}

func TestEntityTypesHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	e := &EntityTypesHolder{ShortName: &zeroValue}
	e.GetShortName()
	e = &EntityTypesHolder{}
	e.GetShortName()
	e = nil
	e.GetShortName()
}

func TestInboundCallsHolder_GetAddRemarksToSummary(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{AddRemarksToSummary: &zeroValue}
	i.GetAddRemarksToSummary()
	i = &InboundCallsHolder{}
	i.GetAddRemarksToSummary()
	i = nil
	i.GetAddRemarksToSummary()
}

func TestInboundCallsHolder_GetCallAcknowledgeTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCallAcknowledgeTime()
	i = nil
	i.GetCallAcknowledgeTime()
}

func TestInboundCallsHolder_GetCallCloseTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCallCloseTime()
	i = nil
	i.GetCallCloseTime()
}

func TestInboundCallsHolder_GetCaller(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCaller()
	i = nil
	i.GetCaller()
}

func TestInboundCallsHolder_GetCallOpenTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCallOpenTime()
	i = nil
	i.GetCallOpenTime()
}

func TestInboundCallsHolder_GetCallRecoveryTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCallRecoveryTime()
	i = nil
	i.GetCallRecoveryTime()
}

func TestInboundCallsHolder_GetCallResponseTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCallResponseTime()
	i = nil
	i.GetCallResponseTime()
}

func TestInboundCallsHolder_GetCallSendTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCallSendTime()
	i = nil
	i.GetCallSendTime()
}

func TestInboundCallsHolder_GetCallStartSLATime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCallStartSLATime()
	i = nil
	i.GetCallStartSLATime()
}

func TestInboundCallsHolder_GetCCP(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCCP()
	i = nil
	i.GetCCP()
}

func TestInboundCallsHolder_GetCHD(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCHD()
	i = nil
	i.GetCHD()
}

func TestInboundCallsHolder_GetCustCallID(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustCallID: &zeroValue}
	i.GetCustCallID()
	i = &InboundCallsHolder{}
	i.GetCustCallID()
	i = nil
	i.GetCustCallID()
}

func TestInboundCallsHolder_GetCustomerCategory1(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerCategory1: &zeroValue}
	i.GetCustomerCategory1()
	i = &InboundCallsHolder{}
	i.GetCustomerCategory1()
	i = nil
	i.GetCustomerCategory1()
}

func TestInboundCallsHolder_GetCustomerCategory2(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerCategory2: &zeroValue}
	i.GetCustomerCategory2()
	i = &InboundCallsHolder{}
	i.GetCustomerCategory2()
	i = nil
	i.GetCustomerCategory2()
}

func TestInboundCallsHolder_GetCustomerCategory3(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerCategory3: &zeroValue}
	i.GetCustomerCategory3()
	i = &InboundCallsHolder{}
	i.GetCustomerCategory3()
	i = nil
	i.GetCustomerCategory3()
}

func TestInboundCallsHolder_GetCustomerCategory4(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerCategory4: &zeroValue}
	i.GetCustomerCategory4()
	i = &InboundCallsHolder{}
	i.GetCustomerCategory4()
	i = nil
	i.GetCustomerCategory4()
}

func TestInboundCallsHolder_GetCustomerCategory5(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerCategory5: &zeroValue}
	i.GetCustomerCategory5()
	i = &InboundCallsHolder{}
	i.GetCustomerCategory5()
	i = nil
	i.GetCustomerCategory5()
}

func TestInboundCallsHolder_GetCustomerReasonCategory1(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerReasonCategory1: &zeroValue}
	i.GetCustomerReasonCategory1()
	i = &InboundCallsHolder{}
	i.GetCustomerReasonCategory1()
	i = nil
	i.GetCustomerReasonCategory1()
}

func TestInboundCallsHolder_GetCustomerReasonCategory2(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerReasonCategory2: &zeroValue}
	i.GetCustomerReasonCategory2()
	i = &InboundCallsHolder{}
	i.GetCustomerReasonCategory2()
	i = nil
	i.GetCustomerReasonCategory2()
}

func TestInboundCallsHolder_GetCustomerReasonCategory3(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerReasonCategory3: &zeroValue}
	i.GetCustomerReasonCategory3()
	i = &InboundCallsHolder{}
	i.GetCustomerReasonCategory3()
	i = nil
	i.GetCustomerReasonCategory3()
}

func TestInboundCallsHolder_GetCustomerReasonCategory4(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerReasonCategory4: &zeroValue}
	i.GetCustomerReasonCategory4()
	i = &InboundCallsHolder{}
	i.GetCustomerReasonCategory4()
	i = nil
	i.GetCustomerReasonCategory4()
}

func TestInboundCallsHolder_GetCustomerReasonCategory5(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{CustomerReasonCategory5: &zeroValue}
	i.GetCustomerReasonCategory5()
	i = &InboundCallsHolder{}
	i.GetCustomerReasonCategory5()
	i = nil
	i.GetCustomerReasonCategory5()
}

func TestInboundCallsHolder_GetCustomerRequestedEndTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCustomerRequestedEndTime()
	i = nil
	i.GetCustomerRequestedEndTime()
}

func TestInboundCallsHolder_GetCustomerRequestedStartTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetCustomerRequestedStartTime()
	i = nil
	i.GetCustomerRequestedStartTime()
}

func TestInboundCallsHolder_GetDescription(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{Description: &zeroValue}
	i.GetDescription()
	i = &InboundCallsHolder{}
	i.GetDescription()
	i = nil
	i.GetDescription()
}

func TestInboundCallsHolder_GetDiagnosis(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{Diagnosis: &zeroValue}
	i.GetDiagnosis()
	i = &InboundCallsHolder{}
	i.GetDiagnosis()
	i = nil
	i.GetDiagnosis()
}

func TestInboundCallsHolder_GetMainComp(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetMainComp()
	i = nil
	i.GetMainComp()
}

func TestInboundCallsHolder_GetOwnership(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{Ownership: &zeroValue}
	i.GetOwnership()
	i = &InboundCallsHolder{}
	i.GetOwnership()
	i = nil
	i.GetOwnership()
}

func TestInboundCallsHolder_GetPartnerCoreTicketId(tt *testing.T) {
	var zeroValue float32
	i := &InboundCallsHolder{PartnerCoreTicketId: &zeroValue}
	i.GetPartnerCoreTicketId()
	i = &InboundCallsHolder{}
	i.GetPartnerCoreTicketId()
	i = nil
	i.GetPartnerCoreTicketId()
}

func TestInboundCallsHolder_GetProblemStartTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetProblemStartTime()
	i = nil
	i.GetProblemStartTime()
}

func TestInboundCallsHolder_GetProviderCategory1(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderCategory1: &zeroValue}
	i.GetProviderCategory1()
	i = &InboundCallsHolder{}
	i.GetProviderCategory1()
	i = nil
	i.GetProviderCategory1()
}

func TestInboundCallsHolder_GetProviderCategory2(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderCategory2: &zeroValue}
	i.GetProviderCategory2()
	i = &InboundCallsHolder{}
	i.GetProviderCategory2()
	i = nil
	i.GetProviderCategory2()
}

func TestInboundCallsHolder_GetProviderCategory3(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderCategory3: &zeroValue}
	i.GetProviderCategory3()
	i = &InboundCallsHolder{}
	i.GetProviderCategory3()
	i = nil
	i.GetProviderCategory3()
}

func TestInboundCallsHolder_GetProviderCategory4(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderCategory4: &zeroValue}
	i.GetProviderCategory4()
	i = &InboundCallsHolder{}
	i.GetProviderCategory4()
	i = nil
	i.GetProviderCategory4()
}

func TestInboundCallsHolder_GetProviderCategory5(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderCategory5: &zeroValue}
	i.GetProviderCategory5()
	i = &InboundCallsHolder{}
	i.GetProviderCategory5()
	i = nil
	i.GetProviderCategory5()
}

func TestInboundCallsHolder_GetProviderReasonCategory1(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderReasonCategory1: &zeroValue}
	i.GetProviderReasonCategory1()
	i = &InboundCallsHolder{}
	i.GetProviderReasonCategory1()
	i = nil
	i.GetProviderReasonCategory1()
}

func TestInboundCallsHolder_GetProviderReasonCategory2(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderReasonCategory2: &zeroValue}
	i.GetProviderReasonCategory2()
	i = &InboundCallsHolder{}
	i.GetProviderReasonCategory2()
	i = nil
	i.GetProviderReasonCategory2()
}

func TestInboundCallsHolder_GetProviderReasonCategory3(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderReasonCategory3: &zeroValue}
	i.GetProviderReasonCategory3()
	i = &InboundCallsHolder{}
	i.GetProviderReasonCategory3()
	i = nil
	i.GetProviderReasonCategory3()
}

func TestInboundCallsHolder_GetProviderReasonCategory4(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderReasonCategory4: &zeroValue}
	i.GetProviderReasonCategory4()
	i = &InboundCallsHolder{}
	i.GetProviderReasonCategory4()
	i = nil
	i.GetProviderReasonCategory4()
}

func TestInboundCallsHolder_GetProviderReasonCategory5(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ProviderReasonCategory5: &zeroValue}
	i.GetProviderReasonCategory5()
	i = &InboundCallsHolder{}
	i.GetProviderReasonCategory5()
	i = nil
	i.GetProviderReasonCategory5()
}

func TestInboundCallsHolder_GetProviderScheduledEndTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetProviderScheduledEndTime()
	i = nil
	i.GetProviderScheduledEndTime()
}

func TestInboundCallsHolder_GetProviderScheduledStartTime(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetProviderScheduledStartTime()
	i = nil
	i.GetProviderScheduledStartTime()
}

func TestInboundCallsHolder_GetRemarks(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{Remarks: &zeroValue}
	i.GetRemarks()
	i = &InboundCallsHolder{}
	i.GetRemarks()
	i = nil
	i.GetRemarks()
}

func TestInboundCallsHolder_GetSDCallID(tt *testing.T) {
	var zeroValue float32
	i := &InboundCallsHolder{SDCallID: &zeroValue}
	i.GetSDCallID()
	i = &InboundCallsHolder{}
	i.GetSDCallID()
	i = nil
	i.GetSDCallID()
}

func TestInboundCallsHolder_GetShortDescription(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{ShortDescription: &zeroValue}
	i.GetShortDescription()
	i = &InboundCallsHolder{}
	i.GetShortDescription()
	i = nil
	i.GetShortDescription()
}

func TestInboundCallsHolder_GetSolution(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{Solution: &zeroValue}
	i.GetSolution()
	i = &InboundCallsHolder{}
	i.GetSolution()
	i = nil
	i.GetSolution()
}

func TestInboundCallsHolder_GetSPCallID(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SPCallID: &zeroValue}
	i.GetSPCallID()
	i = &InboundCallsHolder{}
	i.GetSPCallID()
	i = nil
	i.GetSPCallID()
}

func TestInboundCallsHolder_GetSubComp(tt *testing.T) {
	i := &InboundCallsHolder{}
	i.GetSubComp()
	i = nil
	i.GetSubComp()
}

func TestInboundCallsHolder_GetSysSpecField1(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField1: &zeroValue}
	i.GetSysSpecField1()
	i = &InboundCallsHolder{}
	i.GetSysSpecField1()
	i = nil
	i.GetSysSpecField1()
}

func TestInboundCallsHolder_GetSysSpecField10(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField10: &zeroValue}
	i.GetSysSpecField10()
	i = &InboundCallsHolder{}
	i.GetSysSpecField10()
	i = nil
	i.GetSysSpecField10()
}

func TestInboundCallsHolder_GetSysSpecField2(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField2: &zeroValue}
	i.GetSysSpecField2()
	i = &InboundCallsHolder{}
	i.GetSysSpecField2()
	i = nil
	i.GetSysSpecField2()
}

func TestInboundCallsHolder_GetSysSpecField3(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField3: &zeroValue}
	i.GetSysSpecField3()
	i = &InboundCallsHolder{}
	i.GetSysSpecField3()
	i = nil
	i.GetSysSpecField3()
}

func TestInboundCallsHolder_GetSysSpecField4(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField4: &zeroValue}
	i.GetSysSpecField4()
	i = &InboundCallsHolder{}
	i.GetSysSpecField4()
	i = nil
	i.GetSysSpecField4()
}

func TestInboundCallsHolder_GetSysSpecField5(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField5: &zeroValue}
	i.GetSysSpecField5()
	i = &InboundCallsHolder{}
	i.GetSysSpecField5()
	i = nil
	i.GetSysSpecField5()
}

func TestInboundCallsHolder_GetSysSpecField6(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField6: &zeroValue}
	i.GetSysSpecField6()
	i = &InboundCallsHolder{}
	i.GetSysSpecField6()
	i = nil
	i.GetSysSpecField6()
}

func TestInboundCallsHolder_GetSysSpecField7(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField7: &zeroValue}
	i.GetSysSpecField7()
	i = &InboundCallsHolder{}
	i.GetSysSpecField7()
	i = nil
	i.GetSysSpecField7()
}

func TestInboundCallsHolder_GetSysSpecField8(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField8: &zeroValue}
	i.GetSysSpecField8()
	i = &InboundCallsHolder{}
	i.GetSysSpecField8()
	i = nil
	i.GetSysSpecField8()
}

func TestInboundCallsHolder_GetSysSpecField9(tt *testing.T) {
	var zeroValue string
	i := &InboundCallsHolder{SysSpecField9: &zeroValue}
	i.GetSysSpecField9()
	i = &InboundCallsHolder{}
	i.GetSysSpecField9()
	i = nil
	i.GetSysSpecField9()
}

func TestInboundContractElementsHolder_GetCompLocation(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{CompLocation: &zeroValue}
	i.GetCompLocation()
	i = &InboundContractElementsHolder{}
	i.GetCompLocation()
	i = nil
	i.GetCompLocation()
}

func TestInboundContractElementsHolder_GetComponent(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{Component: &zeroValue}
	i.GetComponent()
	i = &InboundContractElementsHolder{}
	i.GetComponent()
	i = nil
	i.GetComponent()
}

func TestInboundContractElementsHolder_GetContractIDCust(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{ContractIDCust: &zeroValue}
	i.GetContractIDCust()
	i = &InboundContractElementsHolder{}
	i.GetContractIDCust()
	i = nil
	i.GetContractIDCust()
}

func TestInboundContractElementsHolder_GetContractIDProv(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{ContractIDProv: &zeroValue}
	i.GetContractIDProv()
	i = &InboundContractElementsHolder{}
	i.GetContractIDProv()
	i = nil
	i.GetContractIDProv()
}

func TestInboundContractElementsHolder_GetCustomerCategory1(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{CustomerCategory1: &zeroValue}
	i.GetCustomerCategory1()
	i = &InboundContractElementsHolder{}
	i.GetCustomerCategory1()
	i = nil
	i.GetCustomerCategory1()
}

func TestInboundContractElementsHolder_GetCustomerCategory2(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{CustomerCategory2: &zeroValue}
	i.GetCustomerCategory2()
	i = &InboundContractElementsHolder{}
	i.GetCustomerCategory2()
	i = nil
	i.GetCustomerCategory2()
}

func TestInboundContractElementsHolder_GetCustomerCategory3(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{CustomerCategory3: &zeroValue}
	i.GetCustomerCategory3()
	i = &InboundContractElementsHolder{}
	i.GetCustomerCategory3()
	i = nil
	i.GetCustomerCategory3()
}

func TestInboundContractElementsHolder_GetCustomerCategory4(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{CustomerCategory4: &zeroValue}
	i.GetCustomerCategory4()
	i = &InboundContractElementsHolder{}
	i.GetCustomerCategory4()
	i = nil
	i.GetCustomerCategory4()
}

func TestInboundContractElementsHolder_GetCustomerCategory5(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{CustomerCategory5: &zeroValue}
	i.GetCustomerCategory5()
	i = &InboundContractElementsHolder{}
	i.GetCustomerCategory5()
	i = nil
	i.GetCustomerCategory5()
}

func TestInboundContractElementsHolder_GetName(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{Name: &zeroValue}
	i.GetName()
	i = &InboundContractElementsHolder{}
	i.GetName()
	i = nil
	i.GetName()
}

func TestInboundContractElementsHolder_GetNewName(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{NewName: &zeroValue}
	i.GetNewName()
	i = &InboundContractElementsHolder{}
	i.GetNewName()
	i = nil
	i.GetNewName()
}

func TestInboundContractElementsHolder_GetNewShortName(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{NewShortName: &zeroValue}
	i.GetNewShortName()
	i = &InboundContractElementsHolder{}
	i.GetNewShortName()
	i = nil
	i.GetNewShortName()
}

func TestInboundContractElementsHolder_GetProviderCategory1(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{ProviderCategory1: &zeroValue}
	i.GetProviderCategory1()
	i = &InboundContractElementsHolder{}
	i.GetProviderCategory1()
	i = nil
	i.GetProviderCategory1()
}

func TestInboundContractElementsHolder_GetProviderCategory2(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{ProviderCategory2: &zeroValue}
	i.GetProviderCategory2()
	i = &InboundContractElementsHolder{}
	i.GetProviderCategory2()
	i = nil
	i.GetProviderCategory2()
}

func TestInboundContractElementsHolder_GetProviderCategory3(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{ProviderCategory3: &zeroValue}
	i.GetProviderCategory3()
	i = &InboundContractElementsHolder{}
	i.GetProviderCategory3()
	i = nil
	i.GetProviderCategory3()
}

func TestInboundContractElementsHolder_GetProviderCategory4(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{ProviderCategory4: &zeroValue}
	i.GetProviderCategory4()
	i = &InboundContractElementsHolder{}
	i.GetProviderCategory4()
	i = nil
	i.GetProviderCategory4()
}

func TestInboundContractElementsHolder_GetProviderCategory5(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{ProviderCategory5: &zeroValue}
	i.GetProviderCategory5()
	i = &InboundContractElementsHolder{}
	i.GetProviderCategory5()
	i = nil
	i.GetProviderCategory5()
}

func TestInboundContractElementsHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	i := &InboundContractElementsHolder{ShortName: &zeroValue}
	i.GetShortName()
	i = &InboundContractElementsHolder{}
	i.GetShortName()
	i = nil
	i.GetShortName()
}

func TestInboundContractsHolder_GetBPartnerShortNameCust(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{BPartnerShortNameCust: &zeroValue}
	i.GetBPartnerShortNameCust()
	i = &InboundContractsHolder{}
	i.GetBPartnerShortNameCust()
	i = nil
	i.GetBPartnerShortNameCust()
}

func TestInboundContractsHolder_GetBPartnerShortNameProv(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{BPartnerShortNameProv: &zeroValue}
	i.GetBPartnerShortNameProv()
	i = &InboundContractsHolder{}
	i.GetBPartnerShortNameProv()
	i = nil
	i.GetBPartnerShortNameProv()
}

func TestInboundContractsHolder_GetBPOrganizationShortNameCust(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{BPOrganizationShortNameCust: &zeroValue}
	i.GetBPOrganizationShortNameCust()
	i = &InboundContractsHolder{}
	i.GetBPOrganizationShortNameCust()
	i = nil
	i.GetBPOrganizationShortNameCust()
}

func TestInboundContractsHolder_GetBPOrganizationShortNameProv(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{BPOrganizationShortNameProv: &zeroValue}
	i.GetBPOrganizationShortNameProv()
	i = &InboundContractsHolder{}
	i.GetBPOrganizationShortNameProv()
	i = nil
	i.GetBPOrganizationShortNameProv()
}

func TestInboundContractsHolder_GetContractIDCust(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{ContractIDCust: &zeroValue}
	i.GetContractIDCust()
	i = &InboundContractsHolder{}
	i.GetContractIDCust()
	i = nil
	i.GetContractIDCust()
}

func TestInboundContractsHolder_GetContractIDProv(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{ContractIDProv: &zeroValue}
	i.GetContractIDProv()
	i = &InboundContractsHolder{}
	i.GetContractIDProv()
	i = nil
	i.GetContractIDProv()
}

func TestInboundContractsHolder_GetCustIDProv(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{CustIDProv: &zeroValue}
	i.GetCustIDProv()
	i = &InboundContractsHolder{}
	i.GetCustIDProv()
	i = nil
	i.GetCustIDProv()
}

func TestInboundContractsHolder_GetName(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{Name: &zeroValue}
	i.GetName()
	i = &InboundContractsHolder{}
	i.GetName()
	i = nil
	i.GetName()
}

func TestInboundContractsHolder_GetNewName(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{NewName: &zeroValue}
	i.GetNewName()
	i = &InboundContractsHolder{}
	i.GetNewName()
	i = nil
	i.GetNewName()
}

func TestInboundContractsHolder_GetNewShortName(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{NewShortName: &zeroValue}
	i.GetNewShortName()
	i = &InboundContractsHolder{}
	i.GetNewShortName()
	i = nil
	i.GetNewShortName()
}

func TestInboundContractsHolder_GetProvIDCust(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{ProvIDCust: &zeroValue}
	i.GetProvIDCust()
	i = &InboundContractsHolder{}
	i.GetProvIDCust()
	i = nil
	i.GetProvIDCust()
}

func TestInboundContractsHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	i := &InboundContractsHolder{ShortName: &zeroValue}
	i.GetShortName()
	i = &InboundContractsHolder{}
	i.GetShortName()
	i = nil
	i.GetShortName()
}

func TestIntegerKeyField_GetKey(tt *testing.T) {
	var zeroValue string
	i := &IntegerKeyField{Key: &zeroValue}
	i.GetKey()
	i = &IntegerKeyField{}
	i.GetKey()
	i = nil
	i.GetKey()
}

func TestIntegerKeyField_GetValue(tt *testing.T) {
	i := &IntegerKeyField{}
	i.GetValue()
	i = nil
	i.GetValue()
}

func TestListParams_GetLimit(tt *testing.T) {
	var zeroValue int64
	l := &ListParams{Limit: &zeroValue}
	l.GetLimit()
	l = &ListParams{}
	l.GetLimit()
	l = nil
	l.GetLimit()
}

func TestListParams_GetMaxId(tt *testing.T) {
	var zeroValue int64
	l := &ListParams{MaxId: &zeroValue}
	l.GetMaxId()
	l = &ListParams{}
	l.GetMaxId()
	l = nil
	l.GetMaxId()
}

func TestListParams_GetSinceId(tt *testing.T) {
	var zeroValue int64
	l := &ListParams{SinceId: &zeroValue}
	l.GetSinceId()
	l = &ListParams{}
	l.GetSinceId()
	l = nil
	l.GetSinceId()
}

func TestLocationsHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	l := &LocationsHolder{ShortName: &zeroValue}
	l.GetShortName()
	l = &LocationsHolder{}
	l.GetShortName()
	l = nil
	l.GetShortName()
}

func TestParentCallsHolder_GetCustCallID(tt *testing.T) {
	var zeroValue string
	p := &ParentCallsHolder{CustCallID: &zeroValue}
	p.GetCustCallID()
	p = &ParentCallsHolder{}
	p.GetCustCallID()
	p = nil
	p.GetCustCallID()
}

func TestParentCallsHolder_GetSDCallID(tt *testing.T) {
	var zeroValue float32
	p := &ParentCallsHolder{SDCallID: &zeroValue}
	p.GetSDCallID()
	p = &ParentCallsHolder{}
	p.GetSDCallID()
	p = nil
	p.GetSDCallID()
}

func TestParentCallsHolder_GetSPCallID(tt *testing.T) {
	var zeroValue string
	p := &ParentCallsHolder{SPCallID: &zeroValue}
	p.GetSPCallID()
	p = &ParentCallsHolder{}
	p.GetSPCallID()
	p = nil
	p.GetSPCallID()
}

func TestPersonsHolder_GetCategory(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Category: &zeroValue}
	p.GetCategory()
	p = &PersonsHolder{}
	p.GetCategory()
	p = nil
	p.GetCategory()
}

func TestPersonsHolder_GetDepartment(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Department: &zeroValue}
	p.GetDepartment()
	p = &PersonsHolder{}
	p.GetDepartment()
	p = nil
	p.GetDepartment()
}

func TestPersonsHolder_GetDescription(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Description: &zeroValue}
	p.GetDescription()
	p = &PersonsHolder{}
	p.GetDescription()
	p = nil
	p.GetDescription()
}

func TestPersonsHolder_GetEMail(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{EMail: &zeroValue}
	p.GetEMail()
	p = &PersonsHolder{}
	p.GetEMail()
	p = nil
	p.GetEMail()
}

func TestPersonsHolder_GetFax(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Fax: &zeroValue}
	p.GetFax()
	p = &PersonsHolder{}
	p.GetFax()
	p = nil
	p.GetFax()
}

func TestPersonsHolder_GetFirstName(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{FirstName: &zeroValue}
	p.GetFirstName()
	p = &PersonsHolder{}
	p.GetFirstName()
	p = nil
	p.GetFirstName()
}

func TestPersonsHolder_GetLanguage(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Language: &zeroValue}
	p.GetLanguage()
	p = &PersonsHolder{}
	p.GetLanguage()
	p = nil
	p.GetLanguage()
}

func TestPersonsHolder_GetLastName(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{LastName: &zeroValue}
	p.GetLastName()
	p = &PersonsHolder{}
	p.GetLastName()
	p = nil
	p.GetLastName()
}

func TestPersonsHolder_GetLocation(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Location: &zeroValue}
	p.GetLocation()
	p = &PersonsHolder{}
	p.GetLocation()
	p = nil
	p.GetLocation()
}

func TestPersonsHolder_GetLocationCity(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{LocationCity: &zeroValue}
	p.GetLocationCity()
	p = &PersonsHolder{}
	p.GetLocationCity()
	p = nil
	p.GetLocationCity()
}

func TestPersonsHolder_GetLocationCountry(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{LocationCountry: &zeroValue}
	p.GetLocationCountry()
	p = &PersonsHolder{}
	p.GetLocationCountry()
	p = nil
	p.GetLocationCountry()
}

func TestPersonsHolder_GetLocationProvince(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{LocationProvince: &zeroValue}
	p.GetLocationProvince()
	p = &PersonsHolder{}
	p.GetLocationProvince()
	p = nil
	p.GetLocationProvince()
}

func TestPersonsHolder_GetLocationStreet(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{LocationStreet: &zeroValue}
	p.GetLocationStreet()
	p = &PersonsHolder{}
	p.GetLocationStreet()
	p = nil
	p.GetLocationStreet()
}

func TestPersonsHolder_GetLocationZip(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{LocationZip: &zeroValue}
	p.GetLocationZip()
	p = &PersonsHolder{}
	p.GetLocationZip()
	p = nil
	p.GetLocationZip()
}

func TestPersonsHolder_GetMobileTel(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{MobileTel: &zeroValue}
	p.GetMobileTel()
	p = &PersonsHolder{}
	p.GetMobileTel()
	p = nil
	p.GetMobileTel()
}

func TestPersonsHolder_GetPIN(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{PIN: &zeroValue}
	p.GetPIN()
	p = &PersonsHolder{}
	p.GetPIN()
	p = nil
	p.GetPIN()
}

func TestPersonsHolder_GetRoom(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Room: &zeroValue}
	p.GetRoom()
	p = &PersonsHolder{}
	p.GetRoom()
	p = nil
	p.GetRoom()
}

func TestPersonsHolder_GetSalutation(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Salutation: &zeroValue}
	p.GetSalutation()
	p = &PersonsHolder{}
	p.GetSalutation()
	p = nil
	p.GetSalutation()
}

func TestPersonsHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{ShortName: &zeroValue}
	p.GetShortName()
	p = &PersonsHolder{}
	p.GetShortName()
	p = nil
	p.GetShortName()
}

func TestPersonsHolder_GetSign(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Sign: &zeroValue}
	p.GetSign()
	p = &PersonsHolder{}
	p.GetSign()
	p = nil
	p.GetSign()
}

func TestPersonsHolder_GetTel(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Tel: &zeroValue}
	p.GetTel()
	p = &PersonsHolder{}
	p.GetTel()
	p = nil
	p.GetTel()
}

func TestPersonsHolder_GetTel2(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Tel2: &zeroValue}
	p.GetTel2()
	p = &PersonsHolder{}
	p.GetTel2()
	p = nil
	p.GetTel2()
}

func TestPersonsHolder_GetTitle(tt *testing.T) {
	var zeroValue string
	p := &PersonsHolder{Title: &zeroValue}
	p.GetTitle()
	p = &PersonsHolder{}
	p.GetTitle()
	p = nil
	p.GetTitle()
}

func TestQueuesHolder_GetShortName(tt *testing.T) {
	var zeroValue string
	q := &QueuesHolder{ShortName: &zeroValue}
	q.GetShortName()
	q = &QueuesHolder{}
	q.GetShortName()
	q = nil
	q.GetShortName()
}

func TestStringKeyField_GetKey(tt *testing.T) {
	var zeroValue string
	s := &StringKeyField{Key: &zeroValue}
	s.GetKey()
	s = &StringKeyField{}
	s.GetKey()
	s = nil
	s.GetKey()
}

func TestStringKeyField_GetValue(tt *testing.T) {
	var zeroValue string
	s := &StringKeyField{Value: &zeroValue}
	s.GetValue()
	s = &StringKeyField{}
	s.GetValue()
	s = nil
	s.GetValue()
}

func TestTspCode_GetChangeFlag(tt *testing.T) {
	var zeroValue string
	t := &TspCode{ChangeFlag: &zeroValue}
	t.GetChangeFlag()
	t = &TspCode{}
	t.GetChangeFlag()
	t = nil
	t.GetChangeFlag()
}

func TestTspCode_GetEditTimeUtc(tt *testing.T) {
	var zeroValue string
	t := &TspCode{EditTimeUtc: &zeroValue}
	t.GetEditTimeUtc()
	t = &TspCode{}
	t.GetEditTimeUtc()
	t = nil
	t.GetEditTimeUtc()
}

func TestTspCode_GetId(tt *testing.T) {
	t := &TspCode{}
	t.GetId()
	t = nil
	t.GetId()
}

func TestTspCode_GetProblemCodeDescription(tt *testing.T) {
	var zeroValue string
	t := &TspCode{ProblemCodeDescription: &zeroValue}
	t.GetProblemCodeDescription()
	t = &TspCode{}
	t.GetProblemCodeDescription()
	t = nil
	t.GetProblemCodeDescription()
}

func TestTspCode_GetProblemCodeName(tt *testing.T) {
	var zeroValue string
	t := &TspCode{ProblemCodeName: &zeroValue}
	t.GetProblemCodeName()
	t = &TspCode{}
	t.GetProblemCodeName()
	t = nil
	t.GetProblemCodeName()
}

func TestTspCode_GetSubTechId(tt *testing.T) {
	t := &TspCode{}
	t.GetSubTechId()
	t = nil
	t.GetSubTechId()
}

func TestTspCode_GetSubTechName(tt *testing.T) {
	var zeroValue string
	t := &TspCode{SubTechName: &zeroValue}
	t.GetSubTechName()
	t = &TspCode{}
	t.GetSubTechName()
	t = nil
	t.GetSubTechName()
}

func TestTspCode_GetTechId(tt *testing.T) {
	t := &TspCode{}
	t.GetTechId()
	t = nil
	t.GetTechId()
}

func TestTspCode_GetTechName(tt *testing.T) {
	var zeroValue string
	t := &TspCode{TechName: &zeroValue}
	t.GetTechName()
	t = &TspCode{}
	t.GetTechName()
	t = nil
	t.GetTechName()
}
